/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateMagicScanResponseTopHits {
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "priceCents")]
    pub price_cents: f32,
    #[serde(rename = "imageUrl", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[serde(rename = "listingUrl", skip_serializing_if = "Option::is_none")]
    pub listing_url: Option<String>,
    /// Origin marker for the UI badge.
    #[serde(rename = "origin")]
    pub origin: String,
    /// CLIP cosine [0,1]; populated after the visual-rank pass.
    #[serde(rename = "visualSim", skip_serializing_if = "Option::is_none")]
    pub visual_sim: Option<f32>,
    /// 'active' = currently for sale; 'sold' = historical comp. UI  renders distinct badges so the seller can see both at a glance.
    #[serde(rename = "state")]
    pub state: State,
}

impl CreateMagicScanResponseTopHits {
    pub fn new(platform: String, title: String, price_cents: f32, origin: String, state: State) -> CreateMagicScanResponseTopHits {
        CreateMagicScanResponseTopHits {
            platform,
            title,
            price_cents,
            image_url: None,
            listing_url: None,
            origin,
            visual_sim: None,
            state,
        }
    }
}

/// 'active' = currently for sale; 'sold' = historical comp. UI  renders distinct badges so the seller can see both at a glance.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "sold")]
    Sold,
}

impl Default for State {
    fn default() -> State {
        Self::Active
    }
}

