/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxClaimSendResponse {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "txSig", skip_serializing_if = "Option::is_none")]
    pub tx_sig: Option<String>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl CreateCbxClaimSendResponse {
    pub fn new(status: Status) -> CreateCbxClaimSendResponse {
        CreateCbxClaimSendResponse {
            status,
            tx_sig: None,
            reason: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "confirmed")]
    Confirmed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unconfirmed")]
    Unconfirmed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Confirmed
    }
}

