/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateWorkflowChainToggleResponseChain {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "triggerId")]
    pub trigger_id: String,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl CreateWorkflowChainToggleResponseChain {
    pub fn new(id: String, user_id: String, name: String, trigger_id: String, is_active: bool, created_at: String) -> CreateWorkflowChainToggleResponseChain {
        CreateWorkflowChainToggleResponseChain {
            id,
            user_id,
            name,
            trigger_id,
            is_active,
            created_at,
        }
    }
}


