/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTeamInviteResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "inviteeEmail")]
    pub invitee_email: String,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    #[serde(rename = "acceptUrl")]
    pub accept_url: String,
}

impl CreateTeamInviteResponse {
    pub fn new(id: String, invitee_email: String, role: Role, scopes: Vec<String>, expires_at: String, accept_url: String) -> CreateTeamInviteResponse {
        CreateTeamInviteResponse {
            id,
            invitee_email,
            role,
            scopes,
            expires_at,
            accept_url,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "va")]
    Va,
    #[serde(rename = "admin")]
    Admin,
}

impl Default for Role {
    fn default() -> Role {
        Self::Va
    }
}

