/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateBuyerCartQuoteResponse {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "taxCents")]
    pub tax_cents: f32,
    #[serde(rename = "shippingCents")]
    pub shipping_cents: f32,
    #[serde(rename = "totalCents")]
    pub total_cents: f32,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "itemsTotalCents")]
    pub items_total_cents: f32,
    /// Lines being collected in person, so a summary can name what ships free.
    #[serde(rename = "pickupCartItemIds")]
    pub pickup_cart_item_ids: Vec<String>,
    /// False means there is no saved delivery address, so `taxCents` is a floor rather than a final figure — not that tax is zero.
    #[serde(rename = "taxComplete")]
    pub tax_complete: bool,
}

impl CreateBuyerCartQuoteResponse {
    pub fn new(kind: String, tax_cents: f32, shipping_cents: f32, total_cents: f32, currency: String, items_total_cents: f32, pickup_cart_item_ids: Vec<String>, tax_complete: bool) -> CreateBuyerCartQuoteResponse {
        CreateBuyerCartQuoteResponse {
            kind,
            tax_cents,
            shipping_cents,
            total_cents,
            currency,
            items_total_cents,
            pickup_cart_item_ids,
            tax_complete,
        }
    }
}


