/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAiMagicListingResponse {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "suggestedPrice", skip_serializing_if = "Option::is_none")]
    pub suggested_price: Option<Box<crate::models::CreateAiGenerateListingResponseSuggestedPrice>>,
    #[serde(rename = "priceRange", skip_serializing_if = "Option::is_none")]
    pub price_range: Option<Box<crate::models::CreateAiGenerateListingResponsePriceRange>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "subCategory", skip_serializing_if = "Option::is_none")]
    pub sub_category: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "colors", skip_serializing_if = "Option::is_none")]
    pub colors: Option<Box<crate::models::CreateAiGenerateListingResponseColors>>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<crate::models::CreateAiGenerateListingResponseColors>>,
    #[serde(rename = "suggestedTitle", skip_serializing_if = "Option::is_none")]
    pub suggested_title: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "material", skip_serializing_if = "Option::is_none")]
    pub material: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "style", skip_serializing_if = "Option::is_none")]
    pub style: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "itemType", skip_serializing_if = "Option::is_none")]
    pub item_type: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "sizeSystem", skip_serializing_if = "Option::is_none")]
    pub size_system: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
}

impl CreateAiMagicListingResponse {
    pub fn new() -> CreateAiMagicListingResponse {
        CreateAiMagicListingResponse {
            description: None,
            suggested_price: None,
            price_range: None,
            category: None,
            sub_category: None,
            brand: None,
            condition: None,
            colors: None,
            size: None,
            tags: None,
            suggested_title: None,
            material: None,
            style: None,
            pattern: None,
            department: None,
            gender: None,
            item_type: None,
            size_system: None,
        }
    }
}


