/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxAccrualPurchaseResponse {
    #[serde(rename = "accrualId", skip_serializing_if = "Option::is_none")]
    pub accrual_id: Option<String>,
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
    #[serde(rename = "cents")]
    pub cents: f32,
    #[serde(rename = "rateBps", skip_serializing_if = "Option::is_none")]
    pub rate_bps: Option<f32>,
    #[serde(rename = "maturesAt", skip_serializing_if = "Option::is_none")]
    pub matures_at: Option<String>,
    #[serde(rename = "boostBudgetExhausted")]
    pub boost_budget_exhausted: bool,
}

impl CreateCbxAccrualPurchaseResponse {
    pub fn new(duplicate: bool, cents: f32, boost_budget_exhausted: bool) -> CreateCbxAccrualPurchaseResponse {
        CreateCbxAccrualPurchaseResponse {
            accrual_id: None,
            duplicate,
            cents,
            rate_bps: None,
            matures_at: None,
            boost_budget_exhausted,
        }
    }
}


