/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateListingCheckDuplicateResponseMatches {
    /// What we'd offer to do about this match. A suggestion for which button to  feature — never a decision. All three actions stay available.
    #[serde(rename = "suggested")]
    pub suggested: Suggested,
    /// The variation group to ADD to, when the match already belongs to one.  Null means there is no group yet and choosing `variation` creates one from  the match plus the new listing. Without this the UI has to guess, and  guessing wrong means either a second group beside the first or a silent  no-op.
    #[serde(rename = "variationGroupId", skip_serializing_if = "Option::is_none")]
    pub variation_group_id: Option<String>,
    /// The seller's existing listing this scan probably duplicates (null if the  match landed only on an inventory item with no listing row).
    #[serde(rename = "listingId", skip_serializing_if = "Option::is_none")]
    pub listing_id: Option<String>,
    /// The inventory item behind that listing, when linked. Drives the  \"View inventory\" button.
    #[serde(rename = "inventoryItemId", skip_serializing_if = "Option::is_none")]
    pub inventory_item_id: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "imageUrl", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[serde(rename = "matchType")]
    pub match_type: MatchType,
    /// 0–1 confidence. Image matches report 1; title matches the similarity.
    #[serde(rename = "score")]
    pub score: f32,
}

impl CreateListingCheckDuplicateResponseMatches {
    pub fn new(suggested: Suggested, title: String, match_type: MatchType, score: f32) -> CreateListingCheckDuplicateResponseMatches {
        CreateListingCheckDuplicateResponseMatches {
            suggested,
            variation_group_id: None,
            listing_id: None,
            inventory_item_id: None,
            title,
            image_url: None,
            match_type,
            score,
        }
    }
}

/// What we'd offer to do about this match. A suggestion for which button to  feature — never a decision. All three actions stay available.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Suggested {
    #[serde(rename = "variation")]
    Variation,
    #[serde(rename = "restock")]
    Restock,
    #[serde(rename = "duplicate")]
    Duplicate,
}

impl Default for Suggested {
    fn default() -> Suggested {
        Self::Variation
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MatchType {
    #[serde(rename = "title")]
    Title,
    #[serde(rename = "image")]
    Image,
}

impl Default for MatchType {
    fn default() -> MatchType {
        Self::Title
    }
}

