/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxSubjectStakeUnstakeResponse {
    #[serde(rename = "unlocksAt")]
    pub unlocks_at: String,
    #[serde(rename = "cooldownDays")]
    pub cooldown_days: f32,
    #[serde(rename = "baseUnits")]
    pub base_units: String,
}

impl CreateCbxSubjectStakeUnstakeResponse {
    pub fn new(unlocks_at: String, cooldown_days: f32, base_units: String) -> CreateCbxSubjectStakeUnstakeResponse {
        CreateCbxSubjectStakeUnstakeResponse {
            unlocks_at,
            cooldown_days,
            base_units,
        }
    }
}


