/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Vec<String>>,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Vec<String>>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Vec<String>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Vec<String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Vec<String>>,
    #[serde(rename = "platforms", skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<String>>,
    #[serde(rename = "trigger", skip_serializing_if = "Option::is_none")]
    pub trigger: Option<Vec<String>>,
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<Vec<String>>,
    #[serde(rename = "schemaVersion", skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<Vec<String>>,
    #[serde(rename = "exportedAt", skip_serializing_if = "Option::is_none")]
    pub exported_at: Option<Vec<String>>,
    #[serde(rename = "recipes", skip_serializing_if = "Option::is_none")]
    pub recipes: Option<Vec<String>>,
}

impl CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors {
    pub fn new() -> CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors {
        CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors {
            name: None,
            condition: None,
            action: None,
            metadata: None,
            description: None,
            platforms: None,
            trigger: None,
            schema: None,
            schema_version: None,
            exported_at: None,
            recipes: None,
        }
    }
}


