/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateMagicScanSynthesizeResponsePayload {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(rename = "grading", skip_serializing_if = "Option::is_none")]
    pub grading: Option<Box<crate::models::CreateMagicScanSynthesizeResponsePayloadGrading>>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "material", skip_serializing_if = "Option::is_none")]
    pub material: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    /// Poshmark/Vestiaire size system — \"US\", \"EU\", \"UK\", etc.
    #[serde(rename = "sizeSystem", skip_serializing_if = "Option::is_none")]
    pub size_system: Option<String>,
    #[serde(rename = "weightOz", skip_serializing_if = "Option::is_none")]
    pub weight_oz: Option<f32>,
    #[serde(rename = "dimensions", skip_serializing_if = "Option::is_none")]
    pub dimensions: Option<Box<crate::models::CreateMagicScanSynthesizeResponsePayloadDimensions>>,
    /// Echoed user-selected price (cents). Set on every synthesize call  so the master form's defaultPrice input gets populated regardless  of which path (AI or heuristic) generated the rest.
    #[serde(rename = "priceCents", skip_serializing_if = "Option::is_none")]
    pub price_cents: Option<f32>,
    /// The seller's own words about this item — the pre-scan hint, or the  post-scan note that supersedes it (see synthesize/seller-note.ts).  Carried on the payload so the TAXONOMY resolvers see it too: category  and facet picking happen in their own LLM calls, which never saw the  note even after the main synthesis prompt did. A seller correcting the  variant was still getting the category of the wrong one.
    #[serde(rename = "sellerNote", skip_serializing_if = "Option::is_none")]
    pub seller_note: Option<String>,
    /// Comp price band (cents), outlier-trimmed — low/median/high across the  matched comps. The UI surfaces the range so the seller prices  strategically instead of trusting one number; priceCents defaults to  the median when the seller hasn't picked.
    #[serde(rename = "priceLowCents", skip_serializing_if = "Option::is_none")]
    pub price_low_cents: Option<f32>,
    #[serde(rename = "priceMedianCents", skip_serializing_if = "Option::is_none")]
    pub price_median_cents: Option<f32>,
    #[serde(rename = "priceHighCents", skip_serializing_if = "Option::is_none")]
    pub price_high_cents: Option<f32>,
    /// Echoed seller-supplied listable-unit count from Magic List. This is  the listing's ADVERTISED stock (how many of this listing to sell).  Hydrates the form's `quantity` field. Undefined = leave form default (1).
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f32>,
    /// Physical units the seller actually has in stock — becomes the auto-  created inventory item's quantity/quantityAvailable. Distinct from  `quantity` (advertised stock) and `unitsPerListing` (composition).  Undefined = fall back to `quantity`.
    #[serde(rename = "inventoryQuantity", skip_serializing_if = "Option::is_none")]
    pub inventory_quantity: Option<f32>,
    /// How many physical units are bundled inside ONE listing (composition;  e.g. a pack of 4). Becomes listing_inventory_items.quantity so the  multi-channel fulfillable = floor(inventoryQuantity / unitsPerListing).  Undefined = 1.
    #[serde(rename = "unitsPerListing", skip_serializing_if = "Option::is_none")]
    pub units_per_listing: Option<f32>,
    /// What the seller paid, per physical unit, in cents — the auto-created  inventory item's `costBasisCents`. Nothing wrote that column from any  create path, so every Magic List item had a NULL cost basis and every  sale of one reported its full sale price as profit. Undefined = unknown,  which stays NULL (0 would be a claim that the item was free).
    #[serde(rename = "costBasisCents", skip_serializing_if = "Option::is_none")]
    pub cost_basis_cents: Option<f32>,
    #[serde(rename = "chosenDimensions", skip_serializing_if = "Option::is_none")]
    pub chosen_dimensions: Option<Box<crate::models::CreateMagicScanSynthesizeResponsePayloadChosenDimensions>>,
    /// Every photo the seller uploaded for the source scan, primary  first. The NewListingPage hydrator drops these straight into the  form's images state so the seller doesn't have to re-upload.
    #[serde(rename = "imageUrls", skip_serializing_if = "Option::is_none")]
    pub image_urls: Option<Vec<String>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<crate::models::CreateMagicScanSynthesizeResponsePayloadCategory>>,
    /// eBay item-specifics: Department/Gender/Style/Pattern/Type. These  drive the eBay-required aspects on the form's Item Details  section. Mostly only eBay matches have them.
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    #[serde(rename = "style", skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(rename = "itemType", skip_serializing_if = "Option::is_none")]
    pub item_type: Option<String>,
    /// Universal product code, when eBay's enriched detail surfaced it.  Hydrates the master form's UPC/GTIN field.
    #[serde(rename = "upc", skip_serializing_if = "Option::is_none")]
    pub upc: Option<String>,
    #[serde(rename = "handlingTimeDays", skip_serializing_if = "Option::is_none")]
    pub handling_time_days: Option<String>,
    #[serde(rename = "returnWindowDays", skip_serializing_if = "Option::is_none")]
    pub return_window_days: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Master-level item specifics (JSON Record<string,string[]>). Item  specifics are now master-owned + fanned to every aspect platform, so the  form's shared Item-specifics editor prefills from this. Mirrored from the  richest resolved per-platform specifics blob (eBay after full-aspect  enrichment). Undefined = no specifics.
    #[serde(rename = "itemSpecifics", skip_serializing_if = "Option::is_none")]
    pub item_specifics: Option<String>,
    /// Per-platform required-fields map — slotted directly into  platformOverrides when the form hydrates.
    #[serde(rename = "perPlatformOverrides")]
    pub per_platform_overrides: serde_json::Value,
    /// AI's confidence in the synthesis (0-1). Surfaced to the seller  so they can decide whether to skim or trust + click.
    #[serde(rename = "confidence")]
    pub confidence: f32,
    /// AI's free-text rationale for the merge — what it pulled from  where. Helps the seller spot a bad merge before listing.
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "sectionApplicability", skip_serializing_if = "Option::is_none")]
    pub section_applicability: Option<Box<crate::models::CreateMagicScanSynthesizeResponsePayloadSectionApplicability>>,
}

impl CreateMagicScanSynthesizeResponsePayload {
    pub fn new(title: String, description: String, per_platform_overrides: serde_json::Value, confidence: f32) -> CreateMagicScanSynthesizeResponsePayload {
        CreateMagicScanSynthesizeResponsePayload {
            title,
            description,
            brand: None,
            grading: None,
            color: None,
            material: None,
            size: None,
            size_system: None,
            weight_oz: None,
            dimensions: None,
            price_cents: None,
            seller_note: None,
            price_low_cents: None,
            price_median_cents: None,
            price_high_cents: None,
            quantity: None,
            inventory_quantity: None,
            units_per_listing: None,
            cost_basis_cents: None,
            chosen_dimensions: None,
            image_urls: None,
            category: None,
            department: None,
            gender: None,
            style: None,
            pattern: None,
            item_type: None,
            upc: None,
            handling_time_days: None,
            return_window_days: None,
            tags: None,
            item_specifics: None,
            per_platform_overrides,
            confidence,
            notes: None,
            section_applicability: None,
        }
    }
}


