/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxRateQuoteResponse {
    #[serde(rename = "rateBps")]
    pub rate_bps: f32,
    #[serde(rename = "cents")]
    pub cents: f32,
    #[serde(rename = "maturationDays")]
    pub maturation_days: f32,
    #[serde(rename = "source")]
    pub source: Source,
    #[serde(rename = "tierSlug", skip_serializing_if = "Option::is_none")]
    pub tier_slug: Option<String>,
    #[serde(rename = "boostName", skip_serializing_if = "Option::is_none")]
    pub boost_name: Option<String>,
    #[serde(rename = "stakeBoostBps")]
    pub stake_boost_bps: f32,
    #[serde(rename = "clamped")]
    pub clamped: bool,
}

impl CreateCbxRateQuoteResponse {
    pub fn new(rate_bps: f32, cents: f32, maturation_days: f32, source: Source, stake_boost_bps: f32, clamped: bool) -> CreateCbxRateQuoteResponse {
        CreateCbxRateQuoteResponse {
            rate_bps,
            cents,
            maturation_days,
            source,
            tier_slug: None,
            boost_name: None,
            stake_boost_bps,
            clamped,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "tier")]
    Tier,
    #[serde(rename = "base")]
    Base,
    #[serde(rename = "boost")]
    Boost,
}

impl Default for Source {
    fn default() -> Source {
        Self::Tier
    }
}

