/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateBuyerIdentifyResponseVisualMatches {
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "priceCents")]
    pub price_cents: f32,
    #[serde(rename = "imageUrl", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// Cosine similarity. Higher is closer.
    #[serde(rename = "score")]
    pub score: f32,
}

impl CreateBuyerIdentifyResponseVisualMatches {
    pub fn new(slug: String, title: String, price_cents: f32, score: f32) -> CreateBuyerIdentifyResponseVisualMatches {
        CreateBuyerIdentifyResponseVisualMatches {
            slug,
            title,
            price_cents,
            image_url: None,
            score,
        }
    }
}


