/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateInventoryBulkArchiveResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "archived")]
    pub archived: f32,
    #[serde(rename = "bulkJobId")]
    pub bulk_job_id: String,
}

impl CreateInventoryBulkArchiveResponse {
    pub fn new(success: bool, archived: f32, bulk_job_id: String) -> CreateInventoryBulkArchiveResponse {
        CreateInventoryBulkArchiveResponse {
            success,
            archived,
            bulk_job_id,
        }
    }
}


