/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateInboxMessageTriageResponse {
    #[serde(rename = "aiIntent", skip_serializing_if = "Option::is_none")]
    pub ai_intent: Option<String>,
    #[serde(rename = "aiUrgency", skip_serializing_if = "Option::is_none")]
    pub ai_urgency: Option<String>,
    #[serde(rename = "aiScamScore", skip_serializing_if = "Option::is_none")]
    pub ai_scam_score: Option<f32>,
    #[serde(rename = "aiSuggestedReply", skip_serializing_if = "Option::is_none")]
    pub ai_suggested_reply: Option<String>,
    #[serde(rename = "aiTriagedAt", skip_serializing_if = "Option::is_none")]
    pub ai_triaged_at: Option<String>,
}

impl CreateInboxMessageTriageResponse {
    pub fn new() -> CreateInboxMessageTriageResponse {
        CreateInboxMessageTriageResponse {
            ai_intent: None,
            ai_urgency: None,
            ai_scam_score: None,
            ai_suggested_reply: None,
            ai_triaged_at: None,
        }
    }
}


