/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAiGenerateListingResponsePriceRangeValue {
    #[serde(rename = "low")]
    pub low: f32,
    #[serde(rename = "high")]
    pub high: f32,
}

impl CreateAiGenerateListingResponsePriceRangeValue {
    pub fn new(low: f32, high: f32) -> CreateAiGenerateListingResponsePriceRangeValue {
        CreateAiGenerateListingResponsePriceRangeValue {
            low,
            high,
        }
    }
}


