/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxSubjectGrantResponse {
    #[serde(rename = "grantId", skip_serializing_if = "Option::is_none")]
    pub grant_id: Option<String>,
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
}

impl CreateCbxSubjectGrantResponse {
    pub fn new(duplicate: bool) -> CreateCbxSubjectGrantResponse {
        CreateCbxSubjectGrantResponse {
            grant_id: None,
            duplicate,
        }
    }
}


