/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateInventoryCsvImportResponse {
    #[serde(rename = "problems")]
    pub problems: Vec<crate::models::CreateInventoryCsvImportResponseProblems>,
    #[serde(rename = "problemCount")]
    pub problem_count: f32,
    #[serde(rename = "maxRows")]
    pub max_rows: f32,
    #[serde(rename = "created")]
    pub created: f32,
    #[serde(rename = "updated")]
    pub updated: f32,
    /// Rows that mapped cleanly. `created + updated` when not a dry run.
    #[serde(rename = "usable")]
    pub usable: f32,
    #[serde(rename = "totalRows")]
    pub total_rows: f32,
    #[serde(rename = "listingsCreated")]
    pub listings_created: f32,
    /// True when nothing was written — a preview pass.
    #[serde(rename = "dryRun")]
    pub dry_run: bool,
}

impl CreateInventoryCsvImportResponse {
    pub fn new(problems: Vec<crate::models::CreateInventoryCsvImportResponseProblems>, problem_count: f32, max_rows: f32, created: f32, updated: f32, usable: f32, total_rows: f32, listings_created: f32, dry_run: bool) -> CreateInventoryCsvImportResponse {
        CreateInventoryCsvImportResponse {
            problems,
            problem_count,
            max_rows,
            created,
            updated,
            usable,
            total_rows,
            listings_created,
            dry_run,
        }
    }
}


