/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxRedemptionResponse {
    #[serde(rename = "redemptionId")]
    pub redemption_id: String,
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
    #[serde(rename = "baseUnits")]
    pub base_units: String,
    #[serde(rename = "chargedCents")]
    pub charged_cents: f32,
    #[serde(rename = "discountBps")]
    pub discount_bps: f32,
}

impl CreateCbxRedemptionResponse {
    pub fn new(redemption_id: String, duplicate: bool, base_units: String, charged_cents: f32, discount_bps: f32) -> CreateCbxRedemptionResponse {
        CreateCbxRedemptionResponse {
            redemption_id,
            duplicate,
            base_units,
            charged_cents,
            discount_bps,
        }
    }
}


