/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePatResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "prefix")]
    pub prefix: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "environment")]
    pub environment: Environment,
}

impl CreatePatResponse {
    pub fn new(id: String, prefix: String, token: String, name: String, scopes: Vec<String>, environment: Environment) -> CreatePatResponse {
        CreatePatResponse {
            id,
            prefix,
            token,
            name,
            scopes,
            environment,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Environment {
    #[serde(rename = "live")]
    Live,
    #[serde(rename = "test")]
    Test,
}

impl Default for Environment {
    fn default() -> Environment {
        Self::Live
    }
}

