/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxAdCreditPurchaseResponse {
    #[serde(rename = "creditCents")]
    pub credit_cents: f32,
    #[serde(rename = "baseUnitsPaid")]
    pub base_units_paid: String,
    #[serde(rename = "centsPerToken")]
    pub cents_per_token: f32,
    #[serde(rename = "balanceCents")]
    pub balance_cents: f32,
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
}

impl CreateCbxAdCreditPurchaseResponse {
    pub fn new(credit_cents: f32, base_units_paid: String, cents_per_token: f32, balance_cents: f32, duplicate: bool) -> CreateCbxAdCreditPurchaseResponse {
        CreateCbxAdCreditPurchaseResponse {
            credit_cents,
            base_units_paid,
            cents_per_token,
            balance_cents,
            duplicate,
        }
    }
}


