/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateOrderRefundResponse {
    #[serde(rename = "refundId")]
    pub refund_id: String,
    #[serde(rename = "amount")]
    pub amount: f32,
}

impl CreateOrderRefundResponse {
    pub fn new(refund_id: String, amount: f32) -> CreateOrderRefundResponse {
        CreateOrderRefundResponse {
            refund_id,
            amount,
        }
    }
}


