/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxCampaignPreviewResponse {
    #[serde(rename = "recipientCount")]
    pub recipient_count: f32,
    #[serde(rename = "totalBaseUnits")]
    pub total_base_units: String,
    #[serde(rename = "poolBalanceBaseUnits")]
    pub pool_balance_base_units: String,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "allocations")]
    pub allocations: Vec<crate::models::CreateCbxCampaignPreviewResponseAllocations>,
    #[serde(rename = "allocationsTruncated")]
    pub allocations_truncated: bool,
}

impl CreateCbxCampaignPreviewResponse {
    pub fn new(recipient_count: f32, total_base_units: String, pool_balance_base_units: String, hash: String, allocations: Vec<crate::models::CreateCbxCampaignPreviewResponseAllocations>, allocations_truncated: bool) -> CreateCbxCampaignPreviewResponse {
        CreateCbxCampaignPreviewResponse {
            recipient_count,
            total_base_units,
            pool_balance_base_units,
            hash,
            allocations,
            allocations_truncated,
        }
    }
}


