/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateListingMagicFillResponse {
    #[serde(rename = "filled")]
    pub filled: serde_json::Value,
    #[serde(rename = "count")]
    pub count: f32,
    /// False when the seller has no AI provider configured — `count: 0` then means \"nothing new could be resolved\" rather than \"already complete\", a distinction the caller (web's useMagicFill toast) needs but `count` alone can't express. True whenever a provider IS configured, even if the AI call itself failed for some other reason (network, bad key) — that's a different problem than \"connect a provider.\"
    #[serde(rename = "aiAvailable")]
    pub ai_available: bool,
}

impl CreateListingMagicFillResponse {
    pub fn new(filled: serde_json::Value, count: f32, ai_available: bool) -> CreateListingMagicFillResponse {
        CreateListingMagicFillResponse {
            filled,
            count,
            ai_available,
        }
    }
}


