/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxSubjectResponse {
    #[serde(rename = "subjectId")]
    pub subject_id: String,
    #[serde(rename = "externalUserId")]
    pub external_user_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl CreateCbxSubjectResponse {
    pub fn new(subject_id: String, external_user_id: String, created_at: String) -> CreateCbxSubjectResponse {
        CreateCbxSubjectResponse {
            subject_id,
            external_user_id,
            created_at,
        }
    }
}


