/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreatePolicyPresetResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "isDefault")]
    pub is_default: bool,
    #[serde(rename = "kind")]
    pub kind: String,
}

impl CreatePolicyPresetResponse {
    pub fn new(id: String, name: String, created_at: String, updated_at: String, user_id: String, is_default: bool, kind: String) -> CreatePolicyPresetResponse {
        CreatePolicyPresetResponse {
            id,
            name,
            created_at,
            updated_at,
            user_id,
            is_default,
            kind,
        }
    }
}


