/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxClaimQuoteResponse {
    #[serde(rename = "requestedBaseUnits")]
    pub requested_base_units: String,
    #[serde(rename = "serviceFeeBaseUnits")]
    pub service_fee_base_units: String,
    #[serde(rename = "networkFeeBaseUnits")]
    pub network_fee_base_units: String,
    #[serde(rename = "netBaseUnits")]
    pub net_base_units: String,
    #[serde(rename = "requestedCents")]
    pub requested_cents: f32,
    #[serde(rename = "serviceFeeCents")]
    pub service_fee_cents: f32,
    #[serde(rename = "networkFeeCents")]
    pub network_fee_cents: f32,
    #[serde(rename = "netCents")]
    pub net_cents: f32,
    #[serde(rename = "appliedBound")]
    pub applied_bound: String,
}

impl CreateCbxClaimQuoteResponse {
    pub fn new(requested_base_units: String, service_fee_base_units: String, network_fee_base_units: String, net_base_units: String, requested_cents: f32, service_fee_cents: f32, network_fee_cents: f32, net_cents: f32, applied_bound: String) -> CreateCbxClaimQuoteResponse {
        CreateCbxClaimQuoteResponse {
            requested_base_units,
            service_fee_base_units,
            network_fee_base_units,
            net_base_units,
            requested_cents,
            service_fee_cents,
            network_fee_cents,
            net_cents,
            applied_bound,
        }
    }
}


