/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateListingDiscrepancyResolveResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "bulkJobId", skip_serializing_if = "Option::is_none")]
    pub bulk_job_id: Option<String>,
}

impl CreateListingDiscrepancyResolveResponse {
    pub fn new(ok: bool) -> CreateListingDiscrepancyResolveResponse {
        CreateListingDiscrepancyResolveResponse {
            ok,
            bulk_job_id: None,
        }
    }
}


