/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateListingResponse {
    #[serde(rename = "listing")]
    pub listing: Box<crate::models::CreateListingResponseListing>,
    #[serde(rename = "jobs")]
    pub jobs: Vec<crate::models::CreateListingResponseJobs>,
    #[serde(rename = "skipped")]
    pub skipped: Vec<crate::models::CreateListingResponseSkipped>,
    #[serde(rename = "bulkJobId", skip_serializing_if = "Option::is_none")]
    pub bulk_job_id: Option<String>,
}

impl CreateListingResponse {
    pub fn new(listing: crate::models::CreateListingResponseListing, jobs: Vec<crate::models::CreateListingResponseJobs>, skipped: Vec<crate::models::CreateListingResponseSkipped>) -> CreateListingResponse {
        CreateListingResponse {
            listing: Box::new(listing),
            jobs,
            skipped,
            bulk_job_id: None,
        }
    }
}


