/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateListingCombineResponse {
    #[serde(rename = "keepListingId")]
    pub keep_listing_id: String,
    /// Listings archived into the keeper.
    #[serde(rename = "mergedListingIds")]
    pub merged_listing_ids: Vec<String>,
    /// Stock on the keeper's item after summing.
    #[serde(rename = "newQuantityAvailable")]
    pub new_quantity_available: f32,
    /// Units moved off the merged items.
    #[serde(rename = "unitsMoved")]
    pub units_moved: f32,
    /// Delist jobs dispatched for the merged listings' live platforms.
    #[serde(rename = "delistJobsDispatched")]
    pub delist_jobs_dispatched: f32,
}

impl CreateListingCombineResponse {
    pub fn new(keep_listing_id: String, merged_listing_ids: Vec<String>, new_quantity_available: f32, units_moved: f32, delist_jobs_dispatched: f32) -> CreateListingCombineResponse {
        CreateListingCombineResponse {
            keep_listing_id,
            merged_listing_ids,
            new_quantity_available,
            units_moved,
            delist_jobs_dispatched,
        }
    }
}


