/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateOrderBulkMarkShippedResponse {
    #[serde(rename = "updated")]
    pub updated: f32,
    /// Cancelled/refunded orders in the request that were left untouched — reported so a caller can't mistake a partial success for \"all done\" and miss that a closed order was in the batch.
    #[serde(rename = "skipped")]
    pub skipped: f32,
}

impl CreateOrderBulkMarkShippedResponse {
    pub fn new(updated: f32, skipped: f32) -> CreateOrderBulkMarkShippedResponse {
        CreateOrderBulkMarkShippedResponse {
            updated,
            skipped,
        }
    }
}


