/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateBuyerIdentifyResponseHud {
    #[serde(rename = "headline")]
    pub headline: String,
    #[serde(rename = "subline", skip_serializing_if = "Option::is_none")]
    pub subline: Option<String>,
    #[serde(rename = "facts")]
    pub facts: Vec<crate::models::CreateBuyerIdentifyResponseHudFacts>,
    #[serde(rename = "action")]
    pub action: Box<crate::models::CreateBuyerIdentifyResponseHudAction>,
    /// `win` earned a saving, `info` found something, `none` found nothing.
    #[serde(rename = "tone")]
    pub tone: Tone,
    /// Image for the lens card, when there is a match worth showing.
    #[serde(rename = "imageUrl", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
}

impl CreateBuyerIdentifyResponseHud {
    pub fn new(headline: String, facts: Vec<crate::models::CreateBuyerIdentifyResponseHudFacts>, action: crate::models::CreateBuyerIdentifyResponseHudAction, tone: Tone) -> CreateBuyerIdentifyResponseHud {
        CreateBuyerIdentifyResponseHud {
            headline,
            subline: None,
            facts,
            action: Box::new(action),
            tone,
            image_url: None,
        }
    }
}

/// `win` earned a saving, `info` found something, `none` found nothing.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tone {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "win")]
    Win,
}

impl Default for Tone {
    fn default() -> Tone {
        Self::None
    }
}

