/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateBuyerLockonObserveResponse {
    #[serde(rename = "lockonId")]
    pub lockon_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<Box<crate::models::CreateBuyerIdentifyResponseIdentifier>>,
    /// Present when we could not settle it alone. Show them; a pinch on one is the cheapest, strongest disambiguation available.
    #[serde(rename = "candidates")]
    pub candidates: Vec<crate::models::CreateBuyerLockonObserveResponseCandidates>,
    #[serde(rename = "observationCount")]
    pub observation_count: f32,
    #[serde(rename = "visionCalls")]
    pub vision_calls: f32,
    #[serde(rename = "visionQuotaExhausted")]
    pub vision_quota_exhausted: bool,
    #[serde(rename = "verdict")]
    pub verdict: Verdict,
    #[serde(rename = "crossly", skip_serializing_if = "Option::is_none")]
    pub crossly: Option<Box<crate::models::GetBuyerAnywhereResponseCrossly>>,
    #[serde(rename = "offsite", skip_serializing_if = "Option::is_none")]
    pub offsite: Option<Box<crate::models::GetBuyerAnywhereResponseOffsite>>,
    #[serde(rename = "alternates")]
    pub alternates: Vec<crate::models::GetBuyerAnywhereResponseAlternates>,
    #[serde(rename = "savingCents", skip_serializing_if = "Option::is_none")]
    pub saving_cents: Option<f32>,
    #[serde(rename = "shippingUnknown")]
    pub shipping_unknown: bool,
    #[serde(rename = "hud")]
    pub hud: Box<crate::models::CreateBuyerIdentifyResponseHud>,
}

impl CreateBuyerLockonObserveResponse {
    pub fn new(lockon_id: String, status: String, candidates: Vec<crate::models::CreateBuyerLockonObserveResponseCandidates>, observation_count: f32, vision_calls: f32, vision_quota_exhausted: bool, verdict: Verdict, alternates: Vec<crate::models::GetBuyerAnywhereResponseAlternates>, shipping_unknown: bool, hud: crate::models::CreateBuyerIdentifyResponseHud) -> CreateBuyerLockonObserveResponse {
        CreateBuyerLockonObserveResponse {
            lockon_id,
            status,
            identifier: None,
            candidates,
            observation_count,
            vision_calls,
            vision_quota_exhausted,
            verdict,
            crossly: None,
            offsite: None,
            alternates,
            saving_cents: None,
            shipping_unknown,
            hud: Box::new(hud),
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Verdict {
    #[serde(rename = "crossly_best")]
    CrosslyBest,
    #[serde(rename = "offsite_cheaper")]
    OffsiteCheaper,
    #[serde(rename = "offsite_only")]
    OffsiteOnly,
    #[serde(rename = "no_match")]
    NoMatch,
}

impl Default for Verdict {
    fn default() -> Verdict {
        Self::CrosslyBest
    }
}

