/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSpatialPublicResponseProfileContainers {
    /// Stable key. Persisted on every placement — never renamed.
    #[serde(rename = "key")]
    pub key: String,
    /// What the seller calls it. \"Page 3\", \"Case\", \"Long box\".
    #[serde(rename = "label")]
    pub label: String,
    /// Which hand-authored mesh renders this container. A small closed set — the  art budget lives here and nowhere else.
    #[serde(rename = "model")]
    pub model: String,
    /// Outer bounds, for packing containers into a room.
    #[serde(rename = "size")]
    pub size: serde_json::Value,
    #[serde(rename = "slots")]
    pub slots: serde_json::Value,
}

impl GetSpatialPublicResponseProfileContainers {
    pub fn new(key: String, label: String, model: String, size: serde_json::Value, slots: serde_json::Value) -> GetSpatialPublicResponseProfileContainers {
        GetSpatialPublicResponseProfileContainers {
            key,
            label,
            model,
            size,
            slots,
        }
    }
}


