/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOrderEvidenceResponseArrival {
    #[serde(rename = "state")]
    pub state: State,
    #[serde(rename = "windowHours")]
    pub window_hours: f32,
    #[serde(rename = "requestedAt", skip_serializing_if = "Option::is_none")]
    pub requested_at: Option<String>,
    /// When the window shuts. Null when nothing was ever asked.
    #[serde(rename = "closesAt", skip_serializing_if = "Option::is_none")]
    pub closes_at: Option<String>,
    #[serde(rename = "detail")]
    pub detail: String,
    #[serde(rename = "photos")]
    pub photos: Vec<String>,
}

impl GetOrderEvidenceResponseArrival {
    pub fn new(state: State, window_hours: f32, detail: String, photos: Vec<String>) -> GetOrderEvidenceResponseArrival {
        GetOrderEvidenceResponseArrival {
            state,
            window_hours,
            requested_at: None,
            closes_at: None,
            detail,
            photos,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "not_requested")]
    NotRequested,
    #[serde(rename = "awaiting")]
    Awaiting,
    #[serde(rename = "submitted")]
    Submitted,
    #[serde(rename = "declined")]
    Declined,
    #[serde(rename = "window_closed")]
    WindowClosed,
}

impl Default for State {
    fn default() -> State {
        Self::NotRequested
    }
}

