/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCbxMeResponse {
    #[serde(rename = "merchantId")]
    pub merchant_id: String,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "scopes")]
    pub scopes: Vec<Scopes>,
    #[serde(rename = "terms")]
    pub terms: Box<crate::models::GetCbxMeResponseTerms>,
}

impl GetCbxMeResponse {
    pub fn new(merchant_id: String, scopes: Scopes, terms: crate::models::GetCbxMeResponseTerms) -> GetCbxMeResponse {
        GetCbxMeResponse {
            merchant_id,
            slug: None,
            name: None,
            status: None,
            scopes,
            terms: Box::new(terms),
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scopes {
    #[serde(rename = "campaign")]
    Campaign,
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "accrue")]
    Accrue,
    #[serde(rename = "spend")]
    Spend,
    #[serde(rename = "treasury")]
    Treasury,
}

impl Default for Scopes {
    fn default() -> Scopes {
        Self::Campaign
    }
}

