/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMarketProductResponseVariants {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "sortKey")]
    pub sort_key: f32,
    #[serde(rename = "externalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "externalSource", skip_serializing_if = "Option::is_none")]
    pub external_source: Option<String>,
    #[serde(rename = "externalSyncedAt", skip_serializing_if = "Option::is_none")]
    pub external_synced_at: Option<String>,
    #[serde(rename = "lastSaleCents", skip_serializing_if = "Option::is_none")]
    pub last_sale_cents: Option<f32>,
    #[serde(rename = "tradesCount")]
    pub trades_count: f32,
    #[serde(rename = "skuId")]
    pub sku_id: String,
    #[serde(rename = "lastSaleAt", skip_serializing_if = "Option::is_none")]
    pub last_sale_at: Option<String>,
    #[serde(rename = "bestBidCents", skip_serializing_if = "Option::is_none")]
    pub best_bid_cents: Option<f32>,
    #[serde(rename = "bestAskCents", skip_serializing_if = "Option::is_none")]
    pub best_ask_cents: Option<f32>,
}

impl GetMarketProductResponseVariants {
    pub fn new(id: String, label: String, sort_key: f32, trades_count: f32, sku_id: String) -> GetMarketProductResponseVariants {
        GetMarketProductResponseVariants {
            id,
            label,
            sort_key,
            external_id: None,
            external_source: None,
            external_synced_at: None,
            last_sale_cents: None,
            trades_count,
            sku_id,
            last_sale_at: None,
            best_bid_cents: None,
            best_ask_cents: None,
        }
    }
}


