/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticTodayResponseStreak {
    #[serde(rename = "current")]
    pub current: f32,
    #[serde(rename = "longest")]
    pub longest: f32,
    #[serde(rename = "lastActiveDate", skip_serializing_if = "Option::is_none")]
    pub last_active_date: Option<String>,
}

impl GetAnalyticTodayResponseStreak {
    pub fn new(current: f32, longest: f32) -> GetAnalyticTodayResponseStreak {
        GetAnalyticTodayResponseStreak {
            current,
            longest,
            last_active_date: None,
        }
    }
}


