/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticTodayResponseChecklist {
    #[serde(rename = "ordersToShip")]
    pub orders_to_ship: f32,
    #[serde(rename = "unreadMessages")]
    pub unread_messages: f32,
    #[serde(rename = "listingsStaleEnoughToRelist")]
    pub listings_stale_enough_to_relist: f32,
    #[serde(rename = "draftsWaiting")]
    pub drafts_waiting: f32,
}

impl GetAnalyticTodayResponseChecklist {
    pub fn new(orders_to_ship: f32, unread_messages: f32, listings_stale_enough_to_relist: f32, drafts_waiting: f32) -> GetAnalyticTodayResponseChecklist {
        GetAnalyticTodayResponseChecklist {
            orders_to_ship,
            unread_messages,
            listings_stale_enough_to_relist,
            drafts_waiting,
        }
    }
}


