/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTeamResponseMembers {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "memberUserId")]
    pub member_user_id: String,
    #[serde(rename = "memberEmail", skip_serializing_if = "Option::is_none")]
    pub member_email: Option<String>,
    #[serde(rename = "memberDisplayName", skip_serializing_if = "Option::is_none")]
    pub member_display_name: Option<String>,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "revokedAt", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl GetTeamResponseMembers {
    pub fn new(id: String, member_user_id: String, role: String, scopes: Vec<String>, created_at: String) -> GetTeamResponseMembers {
        GetTeamResponseMembers {
            id,
            member_user_id,
            member_email: None,
            member_display_name: None,
            role,
            scopes,
            revoked_at: None,
            created_at,
        }
    }
}


