/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetConnectionHealthResponse {
    #[serde(rename = "extension")]
    pub extension: Box<crate::models::GetConnectionHealthResponseExtension>,
    #[serde(rename = "accounts")]
    pub accounts: Vec<crate::models::GetConnectionHealthResponseAccounts>,
    #[serde(rename = "generatedAt")]
    pub generated_at: String,
}

impl GetConnectionHealthResponse {
    pub fn new(extension: crate::models::GetConnectionHealthResponseExtension, accounts: Vec<crate::models::GetConnectionHealthResponseAccounts>, generated_at: String) -> GetConnectionHealthResponse {
        GetConnectionHealthResponse {
            extension: Box::new(extension),
            accounts,
            generated_at,
        }
    }
}


