/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetInventoryResponse {
    #[serde(rename = "platformListings")]
    pub platform_listings: Vec<crate::models::GetInventoryResponsePlatformListings>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<crate::models::ListInventoryItemCategory>>,
}

impl GetInventoryResponse {
    pub fn new(platform_listings: Vec<crate::models::GetInventoryResponsePlatformListings>) -> GetInventoryResponse {
        GetInventoryResponse {
            platform_listings,
            category: None,
        }
    }
}


