/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetActionLogFacetResponse {
    #[serde(rename = "platforms")]
    pub platforms: Vec<String>,
    #[serde(rename = "actions")]
    pub actions: Vec<String>,
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
}

impl GetActionLogFacetResponse {
    pub fn new(platforms: Vec<String>, actions: Vec<String>, categories: Vec<String>) -> GetActionLogFacetResponse {
        GetActionLogFacetResponse {
            platforms,
            actions,
            categories,
        }
    }
}


