/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOauthInitResponse {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "correlationId")]
    pub correlation_id: String,
    #[serde(rename = "oneShot")]
    pub one_shot: bool,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "requestUrl")]
    pub request_url: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl GetOauthInitResponse {
    pub fn new(url: String, correlation_id: String, one_shot: bool, status: String, request_url: String, message: String) -> GetOauthInitResponse {
        GetOauthInitResponse {
            url,
            correlation_id,
            one_shot,
            status,
            request_url,
            message,
        }
    }
}


