/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticDashboardResponseRevenueByDay {
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "revenue")]
    pub revenue: f32,
    #[serde(rename = "profit")]
    pub profit: f32,
    #[serde(rename = "listings")]
    pub listings: f32,
}

impl GetAnalyticDashboardResponseRevenueByDay {
    pub fn new(date: String, revenue: f32, profit: f32, listings: f32) -> GetAnalyticDashboardResponseRevenueByDay {
        GetAnalyticDashboardResponseRevenueByDay {
            date,
            revenue,
            profit,
            listings,
        }
    }
}


