/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAutomationRuleExportResponse {
    #[serde(rename = "$schema")]
    pub schema: String,
    #[serde(rename = "schemaVersion")]
    pub schema_version: f32,
    #[serde(rename = "exportedAt")]
    pub exported_at: String,
    #[serde(rename = "recipes")]
    pub recipes: Vec<crate::models::GetAutomationRuleExportResponseRecipes>,
}

impl GetAutomationRuleExportResponse {
    pub fn new(schema: String, schema_version: f32, exported_at: String, recipes: Vec<crate::models::GetAutomationRuleExportResponseRecipes>) -> GetAutomationRuleExportResponse {
        GetAutomationRuleExportResponse {
            schema,
            schema_version,
            exported_at,
            recipes,
        }
    }
}


