/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetSpatialPublicResponseStats : Only the count. `capitalCents` is the seller's spend and never leaves.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSpatialPublicResponseStats {
    #[serde(rename = "itemCount")]
    pub item_count: f32,
}

impl GetSpatialPublicResponseStats {
    /// Only the count. `capitalCents` is the seller's spend and never leaves.
    pub fn new(item_count: f32) -> GetSpatialPublicResponseStats {
        GetSpatialPublicResponseStats {
            item_count,
        }
    }
}


