/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCbxMeResponseTerms {
    #[serde(rename = "earnRateBps")]
    pub earn_rate_bps: f32,
    #[serde(rename = "purchaseMaturationDays")]
    pub purchase_maturation_days: f32,
    #[serde(rename = "claimMinCents")]
    pub claim_min_cents: f32,
    #[serde(rename = "withdrawalFeeBps")]
    pub withdrawal_fee_bps: f32,
    #[serde(rename = "withdrawalFeeMinCents")]
    pub withdrawal_fee_min_cents: f32,
    #[serde(rename = "withdrawalFeeMaxCents")]
    pub withdrawal_fee_max_cents: f32,
    #[serde(rename = "inactivityExpiryDays")]
    pub inactivity_expiry_days: f32,
    #[serde(rename = "claimsEnabled")]
    pub claims_enabled: bool,
}

impl GetCbxMeResponseTerms {
    pub fn new(earn_rate_bps: f32, purchase_maturation_days: f32, claim_min_cents: f32, withdrawal_fee_bps: f32, withdrawal_fee_min_cents: f32, withdrawal_fee_max_cents: f32, inactivity_expiry_days: f32, claims_enabled: bool) -> GetCbxMeResponseTerms {
        GetCbxMeResponseTerms {
            earn_rate_bps,
            purchase_maturation_days,
            claim_min_cents,
            withdrawal_fee_bps,
            withdrawal_fee_min_cents,
            withdrawal_fee_max_cents,
            inactivity_expiry_days,
            claims_enabled,
        }
    }
}


