/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticDashboardResponseRecentSales {
    #[serde(rename = "saleId")]
    pub sale_id: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "platformOrderId", skip_serializing_if = "Option::is_none")]
    pub platform_order_id: Option<String>,
    #[serde(rename = "salePrice", skip_serializing_if = "Option::is_none")]
    pub sale_price: Option<f32>,
    #[serde(rename = "platformFee", skip_serializing_if = "Option::is_none")]
    pub platform_fee: Option<f32>,
    #[serde(rename = "shippingCost", skip_serializing_if = "Option::is_none")]
    pub shipping_cost: Option<f32>,
    #[serde(rename = "costOfGoods", skip_serializing_if = "Option::is_none")]
    pub cost_of_goods: Option<f32>,
    #[serde(rename = "netProfit", skip_serializing_if = "Option::is_none")]
    pub net_profit: Option<f32>,
    #[serde(rename = "detectedBy")]
    pub detected_by: String,
    #[serde(rename = "detectedAt")]
    pub detected_at: String,
    #[serde(rename = "itemTitle", skip_serializing_if = "Option::is_none")]
    pub item_title: Option<String>,
    #[serde(rename = "itemImage")]
    pub item_image: String,
}

impl GetAnalyticDashboardResponseRecentSales {
    pub fn new(sale_id: String, platform: String, detected_by: String, detected_at: String, item_image: String) -> GetAnalyticDashboardResponseRecentSales {
        GetAnalyticDashboardResponseRecentSales {
            sale_id,
            platform,
            platform_order_id: None,
            sale_price: None,
            platform_fee: None,
            shipping_cost: None,
            cost_of_goods: None,
            net_profit: None,
            detected_by,
            detected_at,
            item_title: None,
            item_image,
        }
    }
}


