/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSpatialPublicResponseSolvedContainers {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "index")]
    pub index: f32,
    #[serde(rename = "label")]
    pub label: String,
    /// Group path this container primarily holds, for signage on the object.
    #[serde(rename = "groupPath")]
    pub group_path: Vec<String>,
    #[serde(rename = "capacity")]
    pub capacity: f32,
    #[serde(rename = "used")]
    pub used: f32,
}

impl GetSpatialPublicResponseSolvedContainers {
    pub fn new(key: String, index: f32, label: String, group_path: Vec<String>, capacity: f32, used: f32) -> GetSpatialPublicResponseSolvedContainers {
        GetSpatialPublicResponseSolvedContainers {
            key,
            index,
            label,
            group_path,
            capacity,
            used,
        }
    }
}


