/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPlatformLimitResponseEbay {
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "used")]
    pub used: f32,
    #[serde(rename = "limit")]
    pub limit: f32,
    #[serde(rename = "remaining")]
    pub remaining: f32,
    /// False if the user hasn't picked a tier (we default to 250 but flag it so the UI can prompt).
    #[serde(rename = "tierConfigured")]
    pub tier_configured: bool,
    #[serde(rename = "respectQuota")]
    pub respect_quota: bool,
    #[serde(rename = "periodStart")]
    pub period_start: String,
    /// Approximate cost if `used` overflows `limit` — informational.
    #[serde(rename = "perOverageFeeUsd")]
    pub per_overage_fee_usd: f32,
    #[serde(rename = "sellingCap", skip_serializing_if = "Option::is_none")]
    pub selling_cap: Option<Box<crate::models::GetPlatformLimitResponseEbaySellingCap>>,
}

impl GetPlatformLimitResponseEbay {
    pub fn new(platform: String, used: f32, limit: f32, remaining: f32, tier_configured: bool, respect_quota: bool, period_start: String, per_overage_fee_usd: f32) -> GetPlatformLimitResponseEbay {
        GetPlatformLimitResponseEbay {
            platform,
            used,
            limit,
            remaining,
            tier_configured,
            respect_quota,
            period_start,
            per_overage_fee_usd,
            selling_cap: None,
        }
    }
}


