/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAdOffsiteReportResponse {
    #[serde(rename = "spendCents")]
    pub spend_cents: f32,
    #[serde(rename = "mediaCostCents")]
    pub media_cost_cents: f32,
    #[serde(rename = "managementFeeCents")]
    pub management_fee_cents: f32,
    #[serde(rename = "impressions")]
    pub impressions: f32,
    #[serde(rename = "clicks")]
    pub clicks: f32,
    #[serde(rename = "conversions")]
    pub conversions: f32,
    #[serde(rename = "attributedRevenueCents")]
    pub attributed_revenue_cents: f32,
    #[serde(rename = "spilloverConversions")]
    pub spillover_conversions: f32,
    #[serde(rename = "spilloverRevenueCents")]
    pub spillover_revenue_cents: f32,
    #[serde(rename = "returnBps")]
    pub return_bps: f32,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "autoPausedAt", skip_serializing_if = "Option::is_none")]
    pub auto_paused_at: Option<String>,
    #[serde(rename = "autoPausedReason", skip_serializing_if = "Option::is_none")]
    pub auto_paused_reason: Option<String>,
}

impl GetAdOffsiteReportResponse {
    pub fn new(spend_cents: f32, media_cost_cents: f32, management_fee_cents: f32, impressions: f32, clicks: f32, conversions: f32, attributed_revenue_cents: f32, spillover_conversions: f32, spillover_revenue_cents: f32, return_bps: f32, enabled: bool) -> GetAdOffsiteReportResponse {
        GetAdOffsiteReportResponse {
            spend_cents,
            media_cost_cents,
            management_fee_cents,
            impressions,
            clicks,
            conversions,
            attributed_revenue_cents,
            spillover_conversions,
            spillover_revenue_cents,
            return_bps,
            enabled,
            auto_paused_at: None,
            auto_paused_reason: None,
        }
    }
}


