/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticBookkeepingResponseAnnualTotals {
    #[serde(rename = "revenue")]
    pub revenue: f32,
    #[serde(rename = "cogs")]
    pub cogs: f32,
    #[serde(rename = "platformFees")]
    pub platform_fees: f32,
    #[serde(rename = "shippingCosts")]
    pub shipping_costs: f32,
    #[serde(rename = "netProfit")]
    pub net_profit: f32,
}

impl GetAnalyticBookkeepingResponseAnnualTotals {
    pub fn new(revenue: f32, cogs: f32, platform_fees: f32, shipping_costs: f32, net_profit: f32) -> GetAnalyticBookkeepingResponseAnnualTotals {
        GetAnalyticBookkeepingResponseAnnualTotals {
            revenue,
            cogs,
            platform_fees,
            shipping_costs,
            net_profit,
        }
    }
}


