/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetInventoryFacetResponse {
    #[serde(rename = "brands")]
    pub brands: Vec<String>,
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
}

impl GetInventoryFacetResponse {
    pub fn new(brands: Vec<String>, categories: Vec<String>) -> GetInventoryFacetResponse {
        GetInventoryFacetResponse {
            brands,
            categories,
        }
    }
}


