/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticTimeseryResponse {
    #[serde(rename = "days")]
    pub days: f32,
    #[serde(rename = "series")]
    pub series: Vec<crate::models::GetAnalyticTimeseryResponseSeries>,
}

impl GetAnalyticTimeseryResponse {
    pub fn new(days: f32, series: Vec<crate::models::GetAnalyticTimeseryResponseSeries>) -> GetAnalyticTimeseryResponse {
        GetAnalyticTimeseryResponse {
            days,
            series,
        }
    }
}


