/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticTodayResponse {
    #[serde(rename = "checklist")]
    pub checklist: Box<crate::models::GetAnalyticTodayResponseChecklist>,
    #[serde(rename = "streak")]
    pub streak: Box<crate::models::GetAnalyticTodayResponseStreak>,
    #[serde(rename = "activitySparkline")]
    pub activity_sparkline: Vec<f32>,
}

impl GetAnalyticTodayResponse {
    pub fn new(checklist: crate::models::GetAnalyticTodayResponseChecklist, streak: crate::models::GetAnalyticTodayResponseStreak, activity_sparkline: Vec<f32>) -> GetAnalyticTodayResponse {
        GetAnalyticTodayResponse {
            checklist: Box::new(checklist),
            streak: Box::new(streak),
            activity_sparkline,
        }
    }
}


