/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPlatformLimitResponse {
    #[serde(rename = "ebay", skip_serializing_if = "Option::is_none")]
    pub ebay: Option<Box<crate::models::GetPlatformLimitResponseEbay>>,
    #[serde(rename = "etsy", skip_serializing_if = "Option::is_none")]
    pub etsy: Option<Box<crate::models::GetPlatformLimitResponseEtsy>>,
}

impl GetPlatformLimitResponse {
    pub fn new() -> GetPlatformLimitResponse {
        GetPlatformLimitResponse {
            ebay: None,
            etsy: None,
        }
    }
}


