/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetConnectionHealthResponseBrowser : What the browser itself last reported, when it has reported at all.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetConnectionHealthResponseBrowser {
    #[serde(rename = "observations")]
    pub observations: Vec<serde_json::Value>,
    #[serde(rename = "cookieCount")]
    pub cookie_count: f32,
    #[serde(rename = "extensionVersion", skip_serializing_if = "Option::is_none")]
    pub extension_version: Option<String>,
    #[serde(rename = "observedAt")]
    pub observed_at: String,
    #[serde(rename = "observedAgo")]
    pub observed_ago: String,
}

impl GetConnectionHealthResponseBrowser {
    /// What the browser itself last reported, when it has reported at all.
    pub fn new(observations: Vec<serde_json::Value>, cookie_count: f32, observed_at: String, observed_ago: String) -> GetConnectionHealthResponseBrowser {
        GetConnectionHealthResponseBrowser {
            observations,
            cookie_count,
            extension_version: None,
            observed_at,
            observed_ago,
        }
    }
}


