/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetBuyerPreferenceResponsePriceBand : The band they actually shop in, from retail prices they were looking at.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBuyerPreferenceResponsePriceBand {
    #[serde(rename = "p25Cents")]
    pub p25_cents: f32,
    #[serde(rename = "medianCents")]
    pub median_cents: f32,
    #[serde(rename = "p75Cents")]
    pub p75_cents: f32,
}

impl GetBuyerPreferenceResponsePriceBand {
    /// The band they actually shop in, from retail prices they were looking at.
    pub fn new(p25_cents: f32, median_cents: f32, p75_cents: f32) -> GetBuyerPreferenceResponsePriceBand {
        GetBuyerPreferenceResponsePriceBand {
            p25_cents,
            median_cents,
            p75_cents,
        }
    }
}


