/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticBookkeepingResponse {
    #[serde(rename = "year")]
    pub year: f32,
    #[serde(rename = "monthlyPL")]
    pub monthly_pl: Vec<crate::models::GetAnalyticBookkeepingResponseMonthlyPl>,
    #[serde(rename = "annualTotals")]
    pub annual_totals: Box<crate::models::GetAnalyticBookkeepingResponseAnnualTotals>,
    #[serde(rename = "platformBreakdown")]
    pub platform_breakdown: Vec<crate::models::GetAnalyticBookkeepingResponsePlatformBreakdown>,
}

impl GetAnalyticBookkeepingResponse {
    pub fn new(year: f32, monthly_pl: Vec<crate::models::GetAnalyticBookkeepingResponseMonthlyPl>, annual_totals: crate::models::GetAnalyticBookkeepingResponseAnnualTotals, platform_breakdown: Vec<crate::models::GetAnalyticBookkeepingResponsePlatformBreakdown>) -> GetAnalyticBookkeepingResponse {
        GetAnalyticBookkeepingResponse {
            year,
            monthly_pl,
            annual_totals: Box::new(annual_totals),
            platform_breakdown,
        }
    }
}


