/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticDashboardResponseAvgSalePriceByPlatform {
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "avgPrice")]
    pub avg_price: f32,
    #[serde(rename = "count")]
    pub count: String,
}

impl GetAnalyticDashboardResponseAvgSalePriceByPlatform {
    pub fn new(platform: String, avg_price: f32, count: String) -> GetAnalyticDashboardResponseAvgSalePriceByPlatform {
        GetAnalyticDashboardResponseAvgSalePriceByPlatform {
            platform,
            avg_price,
            count,
        }
    }
}


