/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOauthInitResponseOneOf3 {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "requestUrl")]
    pub request_url: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl GetOauthInitResponseOneOf3 {
    pub fn new(status: String, request_url: String, message: String) -> GetOauthInitResponseOneOf3 {
        GetOauthInitResponseOneOf3 {
            status,
            request_url,
            message,
        }
    }
}


