/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOrderEvidenceResponseGradeSignals {
    #[serde(rename = "key")]
    pub key: Key,
    #[serde(rename = "points")]
    pub points: f32,
    /// Shown to the seller verbatim. Must read as a fact, not a verdict.
    #[serde(rename = "detail")]
    pub detail: String,
}

impl GetOrderEvidenceResponseGradeSignals {
    pub fn new(key: Key, points: f32, detail: String) -> GetOrderEvidenceResponseGradeSignals {
        GetOrderEvidenceResponseGradeSignals {
            key,
            points,
            detail,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Key {
    #[serde(rename = "packing_capture")]
    PackingCapture,
    #[serde(rename = "continuous_take")]
    ContinuousTake,
    #[serde(rename = "seal_verified")]
    SealVerified,
    #[serde(rename = "serial_pre_recorded")]
    SerialPreRecorded,
    #[serde(rename = "serial_seen_on_frame")]
    SerialSeenOnFrame,
    #[serde(rename = "arrival_condition")]
    ArrivalCondition,
}

impl Default for Key {
    fn default() -> Key {
        Self::PackingCapture
    }
}

