/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTeamResponseInvitations {
    #[serde(rename = "pending")]
    pub pending: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "inviteeEmail")]
    pub invitee_email: String,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    #[serde(rename = "acceptedAt", skip_serializing_if = "Option::is_none")]
    pub accepted_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl GetTeamResponseInvitations {
    pub fn new(pending: bool, id: String, invitee_email: String, role: String, scopes: Vec<String>, expires_at: String, created_at: String) -> GetTeamResponseInvitations {
        GetTeamResponseInvitations {
            pending,
            id,
            invitee_email,
            role,
            scopes,
            expires_at,
            accepted_at: None,
            created_at,
        }
    }
}


