/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCbxSubjectBalanceBySubjectIdResponse {
    #[serde(rename = "grantedBaseUnits")]
    pub granted_base_units: String,
    #[serde(rename = "earnedBaseUnits")]
    pub earned_base_units: String,
    #[serde(rename = "stakedBaseUnits")]
    pub staked_base_units: String,
    #[serde(rename = "earnedAvailableBaseUnits")]
    pub earned_available_base_units: String,
    #[serde(rename = "connectedAvailableBaseUnits")]
    pub connected_available_base_units: String,
    #[serde(rename = "totalSpendableBaseUnits")]
    pub total_spendable_base_units: String,
}

impl GetCbxSubjectBalanceBySubjectIdResponse {
    pub fn new(granted_base_units: String, earned_base_units: String, staked_base_units: String, earned_available_base_units: String, connected_available_base_units: String, total_spendable_base_units: String) -> GetCbxSubjectBalanceBySubjectIdResponse {
        GetCbxSubjectBalanceBySubjectIdResponse {
            granted_base_units,
            earned_base_units,
            staked_base_units,
            earned_available_base_units,
            connected_available_base_units,
            total_spendable_base_units,
        }
    }
}


