/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSpatialPublicResponseSolvedDividers {
    #[serde(rename = "containerKey")]
    pub container_key: String,
    #[serde(rename = "containerIndex")]
    pub container_index: f32,
    #[serde(rename = "slotIndex")]
    pub slot_index: f32,
    #[serde(rename = "label")]
    pub label: String,
}

impl GetSpatialPublicResponseSolvedDividers {
    pub fn new(container_key: String, container_index: f32, slot_index: f32, label: String) -> GetSpatialPublicResponseSolvedDividers {
        GetSpatialPublicResponseSolvedDividers {
            container_key,
            container_index,
            slot_index,
            label,
        }
    }
}


