/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBuyerCatalogListingAvailabilityResponse {
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "available")]
    pub available: bool,
    #[serde(rename = "quantityAvailable")]
    pub quantity_available: f32,
    #[serde(rename = "priceCents")]
    pub price_cents: f32,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl GetBuyerCatalogListingAvailabilityResponse {
    pub fn new(slug: String, available: bool, quantity_available: f32, price_cents: f32, currency: String, status: String) -> GetBuyerCatalogListingAvailabilityResponse {
        GetBuyerCatalogListingAvailabilityResponse {
            slug,
            available,
            quantity_available,
            price_cents,
            currency,
            status,
        }
    }
}


