/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAccountDeletionStatusResponsePending {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "requestedAt")]
    pub requested_at: String,
    #[serde(rename = "scheduledFor")]
    pub scheduled_for: String,
}

impl GetAccountDeletionStatusResponsePending {
    pub fn new(id: String, requested_at: String, scheduled_for: String) -> GetAccountDeletionStatusResponsePending {
        GetAccountDeletionStatusResponsePending {
            id,
            requested_at,
            scheduled_for,
        }
    }
}


