/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineObject4 {
    #[serde(rename = "namespace")]
    pub namespace: Namespace,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "retailHost", skip_serializing_if = "Option::is_none")]
    pub retail_host: Option<String>,
    #[serde(rename = "pagePriceCents", skip_serializing_if = "Option::is_none")]
    pub page_price_cents: Option<i32>,
    #[serde(rename = "pageCurrency", skip_serializing_if = "Option::is_none")]
    pub page_currency: Option<String>,
}

impl InlineObject4 {
    pub fn new(namespace: Namespace, value: String) -> InlineObject4 {
        InlineObject4 {
            namespace,
            value,
            retail_host: None,
            page_price_cents: None,
            page_currency: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Namespace {
    #[serde(rename = "gtin")]
    Gtin,
    #[serde(rename = "style_code")]
    StyleCode,
    #[serde(rename = "lego_set")]
    LegoSet,
    #[serde(rename = "tcgplayer")]
    Tcgplayer,
    #[serde(rename = "discogs")]
    Discogs,
    #[serde(rename = "asin")]
    Asin,
}

impl Default for Namespace {
    fn default() -> Namespace {
        Self::Gtin
    }
}

