/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListNetworkPoolLogItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "actionType")]
    pub action_type: String,
    #[serde(rename = "targetUserId")]
    pub target_user_id: String,
    #[serde(rename = "performedAt")]
    pub performed_at: String,
    #[serde(rename = "ruleId", skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<String>,
    #[serde(rename = "engagerUserId")]
    pub engager_user_id: String,
    #[serde(rename = "targetListingId", skip_serializing_if = "Option::is_none")]
    pub target_listing_id: Option<String>,
    #[serde(rename = "targetPlatformListingId", skip_serializing_if = "Option::is_none")]
    pub target_platform_listing_id: Option<String>,
}

impl ListNetworkPoolLogItem {
    pub fn new(id: String, platform: String, action_type: String, target_user_id: String, performed_at: String, engager_user_id: String) -> ListNetworkPoolLogItem {
        ListNetworkPoolLogItem {
            id,
            platform,
            action_type,
            target_user_id,
            performed_at,
            rule_id: None,
            engager_user_id,
            target_listing_id: None,
            target_platform_listing_id: None,
        }
    }
}


