/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListBuyerMonitorMatchesItem {
    #[serde(rename = "listingSlug")]
    pub listing_slug: String,
    #[serde(rename = "triggerPriceCents")]
    pub trigger_price_cents: f32,
    #[serde(rename = "deliveredAt", skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl ListBuyerMonitorMatchesItem {
    pub fn new(listing_slug: String, trigger_price_cents: f32, created_at: String) -> ListBuyerMonitorMatchesItem {
        ListBuyerMonitorMatchesItem {
            listing_slug,
            trigger_price_cents,
            delivered_at: None,
            created_at,
        }
    }
}


