/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListBuyerCatalogSearchItem {
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "priceCents")]
    pub price_cents: f32,
    /// MSRP above the ask, or null. Never fabricated from a stale value.
    #[serde(rename = "compareAtCents", skip_serializing_if = "Option::is_none")]
    pub compare_at_cents: Option<f32>,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(rename = "categoryMain", skip_serializing_if = "Option::is_none")]
    pub category_main: Option<String>,
    #[serde(rename = "categorySub", skip_serializing_if = "Option::is_none")]
    pub category_sub: Option<String>,
    #[serde(rename = "thumbnail", skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<String>,
    #[serde(rename = "images")]
    pub images: Vec<String>,
    #[serde(rename = "sellerUsername", skip_serializing_if = "Option::is_none")]
    pub seller_username: Option<String>,
    #[serde(rename = "sellerDisplayName", skip_serializing_if = "Option::is_none")]
    pub seller_display_name: Option<String>,
    /// Units a buyer can actually take right now. Reserved units are excluded.
    #[serde(rename = "quantityAvailable")]
    pub quantity_available: f32,
    #[serde(rename = "listedAt", skip_serializing_if = "Option::is_none")]
    pub listed_at: Option<String>,
    /// Canonical buyer-facing URL, so a client never has to build one.
    #[serde(rename = "url")]
    pub url: String,
}

impl ListBuyerCatalogSearchItem {
    pub fn new(slug: String, title: String, price_cents: f32, currency: String, images: Vec<String>, quantity_available: f32, url: String) -> ListBuyerCatalogSearchItem {
        ListBuyerCatalogSearchItem {
            slug,
            title,
            price_cents,
            compare_at_cents: None,
            currency,
            condition: None,
            brand: None,
            category_main: None,
            category_sub: None,
            thumbnail: None,
            images,
            seller_username: None,
            seller_display_name: None,
            quantity_available,
            listed_at: None,
            url,
        }
    }
}


