/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListTaxonomySuggestItemDisplays : Per-level human labels for `catalog` — lets a caller persist the FLAT department/category/subcategory override keys (matching the web form's picker) with real labels instead of a bare id.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListTaxonomySuggestItemDisplays {
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "feature", skip_serializing_if = "Option::is_none")]
    pub feature: Option<String>,
}

impl ListTaxonomySuggestItemDisplays {
    /// Per-level human labels for `catalog` — lets a caller persist the FLAT department/category/subcategory override keys (matching the web form's picker) with real labels instead of a bare id.
    pub fn new() -> ListTaxonomySuggestItemDisplays {
        ListTaxonomySuggestItemDisplays {
            department: None,
            category: None,
            feature: None,
        }
    }
}


