/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListBuyerCartItem {
    #[serde(rename = "available")]
    pub available: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "platformListingId")]
    pub platform_listing_id: String,
    #[serde(rename = "quantity")]
    pub quantity: f32,
    #[serde(rename = "unitPriceCents")]
    pub unit_price_cents: f32,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "listingStatus", skip_serializing_if = "Option::is_none")]
    pub listing_status: Option<String>,
}

impl ListBuyerCartItem {
    pub fn new(available: bool, id: String, platform_listing_id: String, quantity: f32, unit_price_cents: f32) -> ListBuyerCartItem {
        ListBuyerCartItem {
            available,
            id,
            platform_listing_id,
            quantity,
            unit_price_cents,
            slug: None,
            title: None,
            listing_status: None,
        }
    }
}


