/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListMagicRecentItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "imageUrl")]
    pub image_url: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "topMatchTitle")]
    pub top_match_title: String,
    #[serde(rename = "matchCount")]
    pub match_count: f32,
}

impl ListMagicRecentItem {
    pub fn new(id: String, image_url: String, created_at: String, top_match_title: String, match_count: f32) -> ListMagicRecentItem {
        ListMagicRecentItem {
            id,
            image_url,
            created_at,
            top_match_title,
            match_count,
        }
    }
}


