/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListActionLogCallsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "step", skip_serializing_if = "Option::is_none")]
    pub step: Option<f32>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "method")]
    pub method: String,
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<f32>,
    #[serde(rename = "latencyMs", skip_serializing_if = "Option::is_none")]
    pub latency_ms: Option<f32>,
    #[serde(rename = "errorClass", skip_serializing_if = "Option::is_none")]
    pub error_class: Option<String>,
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "requestBodyExcerpt", skip_serializing_if = "Option::is_none")]
    pub request_body_excerpt: Option<String>,
    #[serde(rename = "responseBodyExcerpt", skip_serializing_if = "Option::is_none")]
    pub response_body_excerpt: Option<String>,
    #[serde(rename = "recipeId", skip_serializing_if = "Option::is_none")]
    pub recipe_id: Option<String>,
    #[serde(rename = "docIdOrHash", skip_serializing_if = "Option::is_none")]
    pub doc_id_or_hash: Option<String>,
    #[serde(rename = "proxyId", skip_serializing_if = "Option::is_none")]
    pub proxy_id: Option<String>,
    #[serde(rename = "correlationId")]
    pub correlation_id: String,
    #[serde(rename = "actionEventId", skip_serializing_if = "Option::is_none")]
    pub action_event_id: Option<String>,
    #[serde(rename = "ok")]
    pub ok: bool,
}

impl ListActionLogCallsItem {
    pub fn new(id: String, created_at: String, platform: String, action: String, url: String, method: String, correlation_id: String, ok: bool) -> ListActionLogCallsItem {
        ListActionLogCallsItem {
            id,
            created_at,
            user_id: None,
            platform,
            action,
            step: None,
            url,
            method,
            status_code: None,
            latency_ms: None,
            error_class: None,
            error_message: None,
            request_body_excerpt: None,
            response_body_excerpt: None,
            recipe_id: None,
            doc_id_or_hash: None,
            proxy_id: None,
            correlation_id,
            action_event_id: None,
            ok,
        }
    }
}


