/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListBuyerCashbackItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "storeName")]
    pub store_name: String,
    #[serde(rename = "storeHost")]
    pub store_host: String,
    #[serde(rename = "orderCents", skip_serializing_if = "Option::is_none")]
    pub order_cents: Option<f32>,
    /// What WE will pay. Never the commission — that is our revenue and is not the shopper's business.
    #[serde(rename = "cashbackCents", skip_serializing_if = "Option::is_none")]
    pub cashback_cents: Option<f32>,
    #[serde(rename = "activatedAt")]
    pub activated_at: String,
    #[serde(rename = "confirmedAt", skip_serializing_if = "Option::is_none")]
    pub confirmed_at: Option<String>,
    #[serde(rename = "paidAt", skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<String>,
    #[serde(rename = "expiredAt", skip_serializing_if = "Option::is_none")]
    pub expired_at: Option<String>,
    #[serde(rename = "rejectedReason", skip_serializing_if = "Option::is_none")]
    pub rejected_reason: Option<String>,
}

impl ListBuyerCashbackItem {
    pub fn new(id: String, status: String, store_name: String, store_host: String, activated_at: String) -> ListBuyerCashbackItem {
        ListBuyerCashbackItem {
            id,
            status,
            store_name,
            store_host,
            order_cents: None,
            cashback_cents: None,
            activated_at,
            confirmed_at: None,
            paid_at: None,
            expired_at: None,
            rejected_reason: None,
        }
    }
}


