/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListCbxCampaignsItem {
    #[serde(rename = "campaignId")]
    pub campaign_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "budgetBaseUnits")]
    pub budget_base_units: String,
    #[serde(rename = "windowStart")]
    pub window_start: String,
    #[serde(rename = "windowEnd")]
    pub window_end: String,
    #[serde(rename = "previewRecipientCount", skip_serializing_if = "Option::is_none")]
    pub preview_recipient_count: Option<f32>,
    #[serde(rename = "executedAt", skip_serializing_if = "Option::is_none")]
    pub executed_at: Option<String>,
}

impl ListCbxCampaignsItem {
    pub fn new(campaign_id: String, name: String, status: String, budget_base_units: String, window_start: String, window_end: String) -> ListCbxCampaignsItem {
        ListCbxCampaignsItem {
            campaign_id,
            name,
            status,
            budget_base_units,
            window_start,
            window_end,
            preview_recipient_count: None,
            executed_at: None,
        }
    }
}


