/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListImportsItemFilters {
    #[serde(rename = "listedAfter", skip_serializing_if = "Option::is_none")]
    pub listed_after: Option<String>,
    #[serde(rename = "listedBefore", skip_serializing_if = "Option::is_none")]
    pub listed_before: Option<String>,
    #[serde(rename = "minPrice", skip_serializing_if = "Option::is_none")]
    pub min_price: Option<f32>,
    #[serde(rename = "maxPrice", skip_serializing_if = "Option::is_none")]
    pub max_price: Option<f32>,
    #[serde(rename = "conditionIncludes", skip_serializing_if = "Option::is_none")]
    pub condition_includes: Option<Vec<String>>,
    #[serde(rename = "maxImport", skip_serializing_if = "Option::is_none")]
    pub max_import: Option<f32>,
}

impl ListImportsItemFilters {
    pub fn new() -> ListImportsItemFilters {
        ListImportsItemFilters {
            listed_after: None,
            listed_before: None,
            min_price: None,
            max_price: None,
            condition_includes: None,
            max_import: None,
        }
    }
}


