/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListSourcingDemandItem {
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "identifierValue")]
    pub identifier_value: String,
    /// How many times anybody looked, in the window.
    #[serde(rename = "looks")]
    pub looks: f32,
    /// How many of those we had nothing for.
    #[serde(rename = "misses")]
    pub misses: f32,
    /// Distinct retailers it was seen on — breadth, not just volume.
    #[serde(rename = "retailers")]
    pub retailers: f32,
    /// What the retailers were charging, median of what we saw.
    #[serde(rename = "medianPageCents", skip_serializing_if = "Option::is_none")]
    pub median_page_cents: Option<f32>,
    #[serde(rename = "lastSeenAt")]
    pub last_seen_at: String,
}

impl ListSourcingDemandItem {
    pub fn new(namespace: String, identifier_value: String, looks: f32, misses: f32, retailers: f32, last_seen_at: String) -> ListSourcingDemandItem {
        ListSourcingDemandItem {
            namespace,
            identifier_value,
            looks,
            misses,
            retailers,
            median_page_cents: None,
            last_seen_at,
        }
    }
}


