/*
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateSavedViewResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "viewMode", skip_serializing_if = "Option::is_none")]
    pub view_mode: Option<String>,
    #[serde(rename = "isDefault")]
    pub is_default: bool,
    #[serde(rename = "sortOrder")]
    pub sort_order: f32,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl UpdateSavedViewResponse {
    pub fn new(id: String, user_id: String, resource: String, name: String, is_default: bool, sort_order: f32, created_at: String, updated_at: String) -> UpdateSavedViewResponse {
        UpdateSavedViewResponse {
            id,
            user_id,
            resource,
            name,
            view_mode: None,
            is_default,
            sort_order,
            created_at,
            updated_at,
        }
    }
}


