/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateInboxMessageTriageResponse {
    #[serde(rename = "aiIntent", skip_serializing_if = "Option::is_none")]
    pub ai_intent: Option<String>,
    #[serde(rename = "aiUrgency", skip_serializing_if = "Option::is_none")]
    pub ai_urgency: Option<String>,
    #[serde(rename = "aiScamScore", skip_serializing_if = "Option::is_none")]
    pub ai_scam_score: Option<f32>,
    #[serde(rename = "aiSuggestedReply", skip_serializing_if = "Option::is_none")]
    pub ai_suggested_reply: Option<String>,
    #[serde(rename = "aiTriagedAt", skip_serializing_if = "Option::is_none")]
    pub ai_triaged_at: Option<String>,
}

impl CreateInboxMessageTriageResponse {
    pub fn new() -> CreateInboxMessageTriageResponse {
        CreateInboxMessageTriageResponse {
            ai_intent: None,
            ai_urgency: None,
            ai_scam_score: None,
            ai_suggested_reply: None,
            ai_triaged_at: None,
        }
    }
}


