/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateMagicScanSynthesizeResponse {
    #[serde(rename = "draftId")]
    pub draft_id: String,
    #[serde(rename = "payload")]
    pub payload: Box<crate::models::CreateMagicScanSynthesizeResponsePayload>,
}

impl CreateMagicScanSynthesizeResponse {
    pub fn new(draft_id: String, payload: crate::models::CreateMagicScanSynthesizeResponsePayload) -> CreateMagicScanSynthesizeResponse {
        CreateMagicScanSynthesizeResponse {
            draft_id,
            payload: Box::new(payload),
        }
    }
}


