/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateListingBulkDelistPreviewResponseMarketplaces {
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "activeCount")]
    pub active_count: f32,
    #[serde(rename = "accountStatus")]
    pub account_status: AccountStatus,
}

impl CreateListingBulkDelistPreviewResponseMarketplaces {
    pub fn new(platform: String, active_count: f32, account_status: AccountStatus) -> CreateListingBulkDelistPreviewResponseMarketplaces {
        CreateListingBulkDelistPreviewResponseMarketplaces {
            platform,
            active_count,
            account_status,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "needs_reauth")]
    NeedsReauth,
}

impl Default for AccountStatus {
    fn default() -> AccountStatus {
        Self::Active
    }
}

