/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxRedemptionQuoteResponse {
    #[serde(rename = "serviceKind")]
    pub service_kind: ServiceKind,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "listPriceCents")]
    pub list_price_cents: f32,
    #[serde(rename = "chargedCents")]
    pub charged_cents: f32,
    #[serde(rename = "discountBps")]
    pub discount_bps: f32,
    #[serde(rename = "baseUnits")]
    pub base_units: String,
    #[serde(rename = "centsPerToken")]
    pub cents_per_token: f32,
}

impl CreateCbxRedemptionQuoteResponse {
    pub fn new(service_kind: ServiceKind, label: String, list_price_cents: f32, charged_cents: f32, discount_bps: f32, base_units: String, cents_per_token: f32) -> CreateCbxRedemptionQuoteResponse {
        CreateCbxRedemptionQuoteResponse {
            service_kind,
            label,
            list_price_cents,
            charged_cents,
            discount_bps,
            base_units,
            cents_per_token,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceKind {
    #[serde(rename = "grading")]
    Grading,
    #[serde(rename = "subscription")]
    Subscription,
    #[serde(rename = "authentication")]
    Authentication,
    #[serde(rename = "evidence_seal")]
    EvidenceSeal,
}

impl Default for ServiceKind {
    fn default() -> ServiceKind {
        Self::Grading
    }
}

