/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAiGenerateListingResponsePriceRange {
    #[serde(rename = "value")]
    pub value: Box<crate::models::CreateAiGenerateListingResponsePriceRangeValue>,
    #[serde(rename = "confidence")]
    pub confidence: f32,
}

impl CreateAiGenerateListingResponsePriceRange {
    pub fn new(value: crate::models::CreateAiGenerateListingResponsePriceRangeValue, confidence: f32) -> CreateAiGenerateListingResponsePriceRange {
        CreateAiGenerateListingResponsePriceRange {
            value: Box::new(value),
            confidence,
        }
    }
}


