/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateOrderPullPlatformLabelResponse {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "persisted")]
    pub persisted: bool,
    #[serde(rename = "expiresInSeconds")]
    pub expires_in_seconds: f32,
    #[serde(rename = "provenance")]
    pub provenance: Provenance,
}

impl CreateOrderPullPlatformLabelResponse {
    pub fn new(url: String, persisted: bool, expires_in_seconds: f32, provenance: Provenance) -> CreateOrderPullPlatformLabelResponse {
        CreateOrderPullPlatformLabelResponse {
            url,
            persisted,
            expires_in_seconds,
            provenance,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provenance {
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "provisional")]
    Provisional,
}

impl Default for Provenance {
    fn default() -> Provenance {
        Self::Verified
    }
}

