/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateMagicScanSynthesizeResponsePayloadSectionApplicability : Deterministic (NO-AI) applicability hint for the heavyweight optional  form sections (vehicle compatibility, EU EPR / energy label, hazmat).  Computed from the resolved category + seller region via  `applicableOptionalSections`; the form pre-checks each section's  \"this item needs …\" toggle from it. Additive + best-effort.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateMagicScanSynthesizeResponsePayloadSectionApplicability {
    /// eBay Motors / Parts vehicle-fitment (compatibilityList).
    #[serde(rename = "vehicleCompat")]
    pub vehicle_compat: bool,
    /// EU/UK Extended Producer Responsibility (packaging/e-waste schemes).
    #[serde(rename = "epr")]
    pub epr: bool,
    /// EU energy-efficiency label (fridges, TVs, lighting, appliances).
    #[serde(rename = "energyLabel")]
    pub energy_label: bool,
    /// Hazmat classification (battery/aerosol/flammable/liquid/chemical).
    #[serde(rename = "hazmat")]
    pub hazmat: bool,
}

impl CreateMagicScanSynthesizeResponsePayloadSectionApplicability {
    /// Deterministic (NO-AI) applicability hint for the heavyweight optional  form sections (vehicle compatibility, EU EPR / energy label, hazmat).  Computed from the resolved category + seller region via  `applicableOptionalSections`; the form pre-checks each section's  \"this item needs …\" toggle from it. Additive + best-effort.
    pub fn new(vehicle_compat: bool, epr: bool, energy_label: bool, hazmat: bool) -> CreateMagicScanSynthesizeResponsePayloadSectionApplicability {
        CreateMagicScanSynthesizeResponsePayloadSectionApplicability {
            vehicle_compat,
            epr,
            energy_label,
            hazmat,
        }
    }
}


