/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateMagicScanResponse {
    #[serde(rename = "runId")]
    pub run_id: String,
    #[serde(rename = "ebayMatch", skip_serializing_if = "Option::is_none")]
    pub ebay_match: Option<Box<crate::models::CreateMagicScanResponseEbayMatch>>,
    /// Unified top-10-globally list, ranked by CLIP visual similarity to  the seller's source photo. Each hit carries its origin platform.
    #[serde(rename = "topHits")]
    pub top_hits: Vec<crate::models::CreateMagicScanResponseTopHits>,
    /// Legacy compat — UI's existing render. ebayHits now == visually-  validated eBay subset; otherMatches is re-grouped from topHits.
    #[serde(rename = "ebayHits")]
    pub ebay_hits: Vec<crate::models::CreateMagicScanResponseEbayHits>,
    #[serde(rename = "otherMatches")]
    pub other_matches: serde_json::Value,
    /// Every photo the seller uploaded for this scan, primary first.
    #[serde(rename = "imageUrls")]
    pub image_urls: Vec<String>,
    /// Vision-LLM aspects extracted across all photos. Populated only  when the seller has magic-list-vision-aspects enabled + a vision  provider configured. Empty otherwise.
    #[serde(rename = "visionAspects")]
    pub vision_aspects: serde_json::Value,
    /// The seller's OWN listings/inventory that this scan probably duplicates  (image + fuzzy-title self-dedup). Empty when nothing matched. Drives the  \"you may already have this\" prompt.
    #[serde(rename = "possibleDuplicates")]
    pub possible_duplicates: Vec<crate::models::CreateMagicScanResponsePossibleDuplicates>,
    #[serde(rename = "cached")]
    pub cached: bool,
}

impl CreateMagicScanResponse {
    pub fn new(run_id: String, top_hits: Vec<crate::models::CreateMagicScanResponseTopHits>, ebay_hits: Vec<crate::models::CreateMagicScanResponseEbayHits>, other_matches: serde_json::Value, image_urls: Vec<String>, vision_aspects: serde_json::Value, possible_duplicates: Vec<crate::models::CreateMagicScanResponsePossibleDuplicates>, cached: bool) -> CreateMagicScanResponse {
        CreateMagicScanResponse {
            run_id,
            ebay_match: None,
            top_hits,
            ebay_hits,
            other_matches,
            image_urls,
            vision_aspects,
            possible_duplicates,
            cached,
        }
    }
}


