/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxSpendResponse {
    #[serde(rename = "spendId")]
    pub spend_id: String,
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
    #[serde(rename = "baseUnitsSpent")]
    pub base_units_spent: String,
    #[serde(rename = "skimTotalBaseUnits")]
    pub skim_total_base_units: String,
    #[serde(rename = "skimEventsBaseUnits")]
    pub skim_events_base_units: String,
    #[serde(rename = "skimPlatformBaseUnits")]
    pub skim_platform_base_units: String,
    #[serde(rename = "skimCappedByOrderFee")]
    pub skim_capped_by_order_fee: bool,
    #[serde(rename = "centsPerToken")]
    pub cents_per_token: f32,
}

impl CreateCbxSpendResponse {
    pub fn new(spend_id: String, duplicate: bool, base_units_spent: String, skim_total_base_units: String, skim_events_base_units: String, skim_platform_base_units: String, skim_capped_by_order_fee: bool, cents_per_token: f32) -> CreateCbxSpendResponse {
        CreateCbxSpendResponse {
            spend_id,
            duplicate,
            base_units_spent,
            skim_total_base_units,
            skim_events_base_units,
            skim_platform_base_units,
            skim_capped_by_order_fee,
            cents_per_token,
        }
    }
}


