/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAccountLogoutAllResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "revokedCount")]
    pub revoked_count: f32,
}

impl CreateAccountLogoutAllResponse {
    pub fn new(ok: bool, revoked_count: f32) -> CreateAccountLogoutAllResponse {
        CreateAccountLogoutAllResponse {
            ok,
            revoked_count,
        }
    }
}


