/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxAdCreditSpendResponse {
    #[serde(rename = "spentCents")]
    pub spent_cents: f32,
    #[serde(rename = "shortfallCents")]
    pub shortfall_cents: f32,
    #[serde(rename = "balanceCents")]
    pub balance_cents: f32,
    #[serde(rename = "poolBaseUnits")]
    pub pool_base_units: String,
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
}

impl CreateCbxAdCreditSpendResponse {
    pub fn new(spent_cents: f32, shortfall_cents: f32, balance_cents: f32, pool_base_units: String, duplicate: bool) -> CreateCbxAdCreditSpendResponse {
        CreateCbxAdCreditSpendResponse {
            spent_cents,
            shortfall_cents,
            balance_cents,
            pool_base_units,
            duplicate,
        }
    }
}


