/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateBuyerCheckoutResponse {
    #[serde(rename = "listingSlug")]
    pub listing_slug: String,
    #[serde(rename = "quantity")]
    pub quantity: f32,
    #[serde(rename = "totalCents")]
    pub total_cents: f32,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "paymentStatus")]
    pub payment_status: String,
    #[serde(rename = "paymentIntentId", skip_serializing_if = "Option::is_none")]
    pub payment_intent_id: Option<String>,
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
}

impl CreateBuyerCheckoutResponse {
    pub fn new(listing_slug: String, quantity: f32, total_cents: f32, currency: String, payment_status: String) -> CreateBuyerCheckoutResponse {
        CreateBuyerCheckoutResponse {
            listing_slug,
            quantity,
            total_cents,
            currency,
            payment_status,
            payment_intent_id: None,
            order_id: None,
        }
    }
}


