/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxSubjectResponse {
    #[serde(rename = "subjectId")]
    pub subject_id: String,
    #[serde(rename = "externalUserId")]
    pub external_user_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl CreateCbxSubjectResponse {
    pub fn new(subject_id: String, external_user_id: String, created_at: String) -> CreateCbxSubjectResponse {
        CreateCbxSubjectResponse {
            subject_id,
            external_user_id,
            created_at,
        }
    }
}


