/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxCreditDrawResponse {
    #[serde(rename = "movementId")]
    pub movement_id: String,
    #[serde(rename = "drawnCents")]
    pub drawn_cents: f32,
    #[serde(rename = "baseUnitsGranted")]
    pub base_units_granted: String,
    #[serde(rename = "dueAt")]
    pub due_at: String,
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
}

impl CreateCbxCreditDrawResponse {
    pub fn new(movement_id: String, drawn_cents: f32, base_units_granted: String, due_at: String, duplicate: bool) -> CreateCbxCreditDrawResponse {
        CreateCbxCreditDrawResponse {
            movement_id,
            drawn_cents,
            base_units_granted,
            due_at,
            duplicate,
        }
    }
}


