/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateInventoryBulkArchiveResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "archived")]
    pub archived: f32,
    #[serde(rename = "bulkJobId")]
    pub bulk_job_id: String,
}

impl CreateInventoryBulkArchiveResponse {
    pub fn new(success: bool, archived: f32, bulk_job_id: String) -> CreateInventoryBulkArchiveResponse {
        CreateInventoryBulkArchiveResponse {
            success,
            archived,
            bulk_job_id,
        }
    }
}


