/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxRedemptionResponse {
    #[serde(rename = "redemptionId")]
    pub redemption_id: String,
    #[serde(rename = "duplicate")]
    pub duplicate: bool,
    #[serde(rename = "baseUnits")]
    pub base_units: String,
    #[serde(rename = "chargedCents")]
    pub charged_cents: f32,
    #[serde(rename = "discountBps")]
    pub discount_bps: f32,
}

impl CreateCbxRedemptionResponse {
    pub fn new(redemption_id: String, duplicate: bool, base_units: String, charged_cents: f32, discount_bps: f32) -> CreateCbxRedemptionResponse {
        CreateCbxRedemptionResponse {
            redemption_id,
            duplicate,
            base_units,
            charged_cents,
            discount_bps,
        }
    }
}


