/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxCreditRefreshResponse {
    #[serde(rename = "creditLineId")]
    pub credit_line_id: String,
    #[serde(rename = "earnedLimitCents")]
    pub earned_limit_cents: f32,
    #[serde(rename = "stakeBonusCents")]
    pub stake_bonus_cents: f32,
    #[serde(rename = "totalLimitCents")]
    pub total_limit_cents: f32,
    #[serde(rename = "rateBps")]
    pub rate_bps: f32,
    #[serde(rename = "termDays")]
    pub term_days: f32,
    #[serde(rename = "status")]
    pub status: String,
}

impl CreateCbxCreditRefreshResponse {
    pub fn new(credit_line_id: String, earned_limit_cents: f32, stake_bonus_cents: f32, total_limit_cents: f32, rate_bps: f32, term_days: f32, status: String) -> CreateCbxCreditRefreshResponse {
        CreateCbxCreditRefreshResponse {
            credit_line_id,
            earned_limit_cents,
            stake_bonus_cents,
            total_limit_cents,
            rate_bps,
            term_days,
            status,
        }
    }
}


