/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTeamInviteResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "inviteeEmail")]
    pub invitee_email: String,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    #[serde(rename = "acceptUrl")]
    pub accept_url: String,
}

impl CreateTeamInviteResponse {
    pub fn new(id: String, invitee_email: String, role: Role, scopes: Vec<String>, expires_at: String, accept_url: String) -> CreateTeamInviteResponse {
        CreateTeamInviteResponse {
            id,
            invitee_email,
            role,
            scopes,
            expires_at,
            accept_url,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "va")]
    Va,
    #[serde(rename = "admin")]
    Admin,
}

impl Default for Role {
    fn default() -> Role {
        Self::Va
    }
}

