/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateBuyerMonitorResponse {
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "pausedReason", skip_serializing_if = "Option::is_none")]
    pub paused_reason: Option<String>,
    #[serde(rename = "matchCount")]
    pub match_count: f32,
    #[serde(rename = "lastCheckedAt", skip_serializing_if = "Option::is_none")]
    pub last_checked_at: Option<String>,
    #[serde(rename = "lastMatchAt", skip_serializing_if = "Option::is_none")]
    pub last_match_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "webhookSecret", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "delivery")]
    pub delivery: Delivery,
    #[serde(rename = "webhookUrl", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
}

impl CreateBuyerMonitorResponse {
    pub fn new(active: bool, match_count: f32, created_at: String, id: String, name: String, kind: Kind, delivery: Delivery) -> CreateBuyerMonitorResponse {
        CreateBuyerMonitorResponse {
            active,
            paused_reason: None,
            match_count,
            last_checked_at: None,
            last_match_at: None,
            created_at,
            webhook_secret: None,
            id,
            name,
            kind,
            delivery,
            webhook_url: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "new_listing")]
    NewListing,
    #[serde(rename = "price_drop")]
    PriceDrop,
    #[serde(rename = "back_in_stock")]
    BackInStock,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::NewListing
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Delivery {
    #[serde(rename = "webhook")]
    Webhook,
    #[serde(rename = "poll")]
    Poll,
}

impl Default for Delivery {
    fn default() -> Delivery {
        Self::Webhook
    }
}

