/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCbxRevenueSweepResponse {
    #[serde(rename = "swept")]
    pub swept: bool,
    #[serde(rename = "baseUnits")]
    pub base_units: String,
    #[serde(rename = "txSig", skip_serializing_if = "Option::is_none")]
    pub tx_sig: Option<String>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::CreateCbxRevenueSweepResponseBreakdown>>,
}

impl CreateCbxRevenueSweepResponse {
    pub fn new(swept: bool, base_units: String) -> CreateCbxRevenueSweepResponse {
        CreateCbxRevenueSweepResponse {
            swept,
            base_units,
            tx_sig: None,
            reason: None,
            breakdown: None,
        }
    }
}


