/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateOrderRefundResponse {
    #[serde(rename = "refundId")]
    pub refund_id: String,
    #[serde(rename = "amount")]
    pub amount: f32,
}

impl CreateOrderRefundResponse {
    pub fn new(refund_id: String, amount: f32) -> CreateOrderRefundResponse {
        CreateOrderRefundResponse {
            refund_id,
            amount,
        }
    }
}


