/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateMagicScanSynthesizeResponsePayloadChosenDimensions : Seller-picked package size (inches). Beats the synthesizer's estimate —  see where it is applied.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateMagicScanSynthesizeResponsePayloadChosenDimensions {
    #[serde(rename = "lengthIn", skip_serializing_if = "Option::is_none")]
    pub length_in: Option<f32>,
    #[serde(rename = "widthIn", skip_serializing_if = "Option::is_none")]
    pub width_in: Option<f32>,
    #[serde(rename = "heightIn", skip_serializing_if = "Option::is_none")]
    pub height_in: Option<f32>,
}

impl CreateMagicScanSynthesizeResponsePayloadChosenDimensions {
    /// Seller-picked package size (inches). Beats the synthesizer's estimate —  see where it is applied.
    pub fn new() -> CreateMagicScanSynthesizeResponsePayloadChosenDimensions {
        CreateMagicScanSynthesizeResponsePayloadChosenDimensions {
            length_in: None,
            width_in: None,
            height_in: None,
        }
    }
}


