/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateOrderMessageResponse {
    #[serde(rename = "orderId")]
    pub order_id: String,
    #[serde(rename = "sent")]
    pub sent: bool,
    #[serde(rename = "platformConversationId")]
    pub platform_conversation_id: String,
}

impl CreateOrderMessageResponse {
    pub fn new(order_id: String, sent: bool, platform_conversation_id: String) -> CreateOrderMessageResponse {
        CreateOrderMessageResponse {
            order_id,
            sent,
            platform_conversation_id,
        }
    }
}


