/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateListingCombineResponse {
    #[serde(rename = "keepListingId")]
    pub keep_listing_id: String,
    /// Listings archived into the keeper.
    #[serde(rename = "mergedListingIds")]
    pub merged_listing_ids: Vec<String>,
    /// Stock on the keeper's item after summing.
    #[serde(rename = "newQuantityAvailable")]
    pub new_quantity_available: f32,
    /// Units moved off the merged items.
    #[serde(rename = "unitsMoved")]
    pub units_moved: f32,
    /// Delist jobs dispatched for the merged listings' live platforms.
    #[serde(rename = "delistJobsDispatched")]
    pub delist_jobs_dispatched: f32,
}

impl CreateListingCombineResponse {
    pub fn new(keep_listing_id: String, merged_listing_ids: Vec<String>, new_quantity_available: f32, units_moved: f32, delist_jobs_dispatched: f32) -> CreateListingCombineResponse {
        CreateListingCombineResponse {
            keep_listing_id,
            merged_listing_ids,
            new_quantity_available,
            units_moved,
            delist_jobs_dispatched,
        }
    }
}


