/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAiCategorizeFromImageResponse {
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "subCategory", skip_serializing_if = "Option::is_none")]
    pub sub_category: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "colors", skip_serializing_if = "Option::is_none")]
    pub colors: Option<Box<crate::models::CreateAiGenerateListingResponseColors>>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<crate::models::CreateAiGenerateListingResponseColors>>,
    #[serde(rename = "suggestedTitle", skip_serializing_if = "Option::is_none")]
    pub suggested_title: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "material", skip_serializing_if = "Option::is_none")]
    pub material: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "style", skip_serializing_if = "Option::is_none")]
    pub style: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "itemType", skip_serializing_if = "Option::is_none")]
    pub item_type: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
    #[serde(rename = "sizeSystem", skip_serializing_if = "Option::is_none")]
    pub size_system: Option<Box<crate::models::CreateAiGenerateListingResponseDescription>>,
}

impl CreateAiCategorizeFromImageResponse {
    pub fn new() -> CreateAiCategorizeFromImageResponse {
        CreateAiCategorizeFromImageResponse {
            category: None,
            sub_category: None,
            brand: None,
            condition: None,
            colors: None,
            size: None,
            tags: None,
            suggested_title: None,
            material: None,
            style: None,
            pattern: None,
            department: None,
            gender: None,
            item_type: None,
            size_system: None,
        }
    }
}


