/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAutomationRuleExportResponseRecipes {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "action")]
    pub action: Box<crate::models::GetAutomationRuleExportResponseAction>,
    #[serde(rename = "trigger")]
    pub trigger: Box<crate::models::GetAutomationRuleExportResponseAction>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: f32,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Box<crate::models::GetAutomationRuleExportResponseCondition>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::GetAutomationRuleExportResponseMetadata>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "platforms", skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<String>>,
    /// Optional reference to the public schema URL — purely cosmetic.
    #[serde(rename = "$schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
}

impl GetAutomationRuleExportResponseRecipes {
    pub fn new(name: String, action: crate::models::GetAutomationRuleExportResponseAction, trigger: crate::models::GetAutomationRuleExportResponseAction, schema_version: f32) -> GetAutomationRuleExportResponseRecipes {
        GetAutomationRuleExportResponseRecipes {
            name,
            action: Box::new(action),
            trigger: Box::new(trigger),
            schema_version,
            condition: None,
            metadata: None,
            description: None,
            platforms: None,
            schema: None,
        }
    }
}


