/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTaxScheduleCResponse {
    #[serde(rename = "year")]
    pub year: f32,
    #[serde(rename = "businessName", skip_serializing_if = "Option::is_none")]
    pub business_name: Option<String>,
    #[serde(rename = "ein", skip_serializing_if = "Option::is_none")]
    pub ein: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "grossReceipts")]
    pub gross_receipts: f32,
    #[serde(rename = "returnsAndAllowances")]
    pub returns_and_allowances: f32,
    #[serde(rename = "netSales")]
    pub net_sales: f32,
    #[serde(rename = "expenses")]
    pub expenses: Box<crate::models::GetTaxScheduleCResponseExpenses>,
    #[serde(rename = "netProfit")]
    pub net_profit: f32,
    #[serde(rename = "counts")]
    pub counts: Box<crate::models::GetTaxScheduleCResponseCounts>,
}

impl GetTaxScheduleCResponse {
    pub fn new(year: f32, gross_receipts: f32, returns_and_allowances: f32, net_sales: f32, expenses: crate::models::GetTaxScheduleCResponseExpenses, net_profit: f32, counts: crate::models::GetTaxScheduleCResponseCounts) -> GetTaxScheduleCResponse {
        GetTaxScheduleCResponse {
            year,
            business_name: None,
            ein: None,
            address: None,
            gross_receipts,
            returns_and_allowances,
            net_sales,
            expenses: Box::new(expenses),
            net_profit,
            counts: Box::new(counts),
        }
    }
}


