/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCbxMeResponse {
    #[serde(rename = "merchantId")]
    pub merchant_id: String,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "scopes")]
    pub scopes: Vec<Scopes>,
    #[serde(rename = "terms")]
    pub terms: Box<crate::models::GetCbxMeResponseTerms>,
}

impl GetCbxMeResponse {
    pub fn new(merchant_id: String, scopes: Scopes, terms: crate::models::GetCbxMeResponseTerms) -> GetCbxMeResponse {
        GetCbxMeResponse {
            merchant_id,
            slug: None,
            name: None,
            status: None,
            scopes,
            terms: Box::new(terms),
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scopes {
    #[serde(rename = "campaign")]
    Campaign,
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "accrue")]
    Accrue,
    #[serde(rename = "spend")]
    Spend,
    #[serde(rename = "treasury")]
    Treasury,
}

impl Default for Scopes {
    fn default() -> Scopes {
        Self::Campaign
    }
}

