/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBuyerPreferenceResponse {
    /// Retailers they shop, most-seen first.
    #[serde(rename = "retailers")]
    pub retailers: Vec<crate::models::GetBuyerPreferenceResponseRetailers>,
    /// What they look at, by catalog brand where we could resolve one.
    #[serde(rename = "brands")]
    pub brands: Vec<crate::models::GetBuyerPreferenceResponseBrands>,
    #[serde(rename = "priceBand", skip_serializing_if = "Option::is_none")]
    pub price_band: Option<Box<crate::models::GetBuyerPreferenceResponsePriceBand>>,
    /// How much of what they want we can actually supply.
    #[serde(rename = "matchRate", skip_serializing_if = "Option::is_none")]
    pub match_rate: Option<f32>,
    #[serde(rename = "observations")]
    pub observations: f32,
}

impl GetBuyerPreferenceResponse {
    pub fn new(retailers: Vec<crate::models::GetBuyerPreferenceResponseRetailers>, brands: Vec<crate::models::GetBuyerPreferenceResponseBrands>, observations: f32) -> GetBuyerPreferenceResponse {
        GetBuyerPreferenceResponse {
            retailers,
            brands,
            price_band: None,
            match_rate: None,
            observations,
        }
    }
}


