/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetInventoryLabelStatResponseLabels {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "itemCount")]
    pub item_count: f32,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
}

impl GetInventoryLabelStatResponseLabels {
    pub fn new(label: String, item_count: f32) -> GetInventoryLabelStatResponseLabels {
        GetInventoryLabelStatResponseLabels {
            label,
            item_count,
            color: None,
        }
    }
}


