/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPayoutGrossForNetResponseEstimate {
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "grossCents")]
    pub gross_cents: f32,
    #[serde(rename = "feeCents")]
    pub fee_cents: f32,
    #[serde(rename = "feeSource")]
    pub fee_source: FeeSource,
    #[serde(rename = "shippingCents")]
    pub shipping_cents: f32,
    #[serde(rename = "shippingSource")]
    pub shipping_source: ShippingSource,
    #[serde(rename = "netCents")]
    pub net_cents: f32,
    /// Net as a percentage of gross, for comparing across price points.
    #[serde(rename = "takeHomePct")]
    pub take_home_pct: f32,
    /// What we assumed, in the seller's words. Never empty when we guessed.
    #[serde(rename = "assumptions")]
    pub assumptions: Vec<String>,
}

impl GetPayoutGrossForNetResponseEstimate {
    pub fn new(platform: String, gross_cents: f32, fee_cents: f32, fee_source: FeeSource, shipping_cents: f32, shipping_source: ShippingSource, net_cents: f32, take_home_pct: f32, assumptions: Vec<String>) -> GetPayoutGrossForNetResponseEstimate {
        GetPayoutGrossForNetResponseEstimate {
            platform,
            gross_cents,
            fee_cents,
            fee_source,
            shipping_cents,
            shipping_source,
            net_cents,
            take_home_pct,
            assumptions,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeeSource {
    #[serde(rename = "exact")]
    Exact,
    #[serde(rename = "estimated")]
    Estimated,
}

impl Default for FeeSource {
    fn default() -> FeeSource {
        Self::Exact
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ShippingSource {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "quoted")]
    Quoted,
    #[serde(rename = "platform_label")]
    PlatformLabel,
    #[serde(rename = "buyer_paid")]
    BuyerPaid,
}

impl Default for ShippingSource {
    fn default() -> ShippingSource {
        Self::None
    }
}

