/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTeamResponseMembers {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "memberUserId")]
    pub member_user_id: String,
    #[serde(rename = "memberEmail", skip_serializing_if = "Option::is_none")]
    pub member_email: Option<String>,
    #[serde(rename = "memberDisplayName", skip_serializing_if = "Option::is_none")]
    pub member_display_name: Option<String>,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "revokedAt", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl GetTeamResponseMembers {
    pub fn new(id: String, member_user_id: String, role: String, scopes: Vec<String>, created_at: String) -> GetTeamResponseMembers {
        GetTeamResponseMembers {
            id,
            member_user_id,
            member_email: None,
            member_display_name: None,
            role,
            scopes,
            revoked_at: None,
            created_at,
        }
    }
}


