/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOrderEvidenceResponseGradeSignals {
    #[serde(rename = "key")]
    pub key: Key,
    #[serde(rename = "points")]
    pub points: f32,
    /// Shown to the seller verbatim. Must read as a fact, not a verdict.
    #[serde(rename = "detail")]
    pub detail: String,
}

impl GetOrderEvidenceResponseGradeSignals {
    pub fn new(key: Key, points: f32, detail: String) -> GetOrderEvidenceResponseGradeSignals {
        GetOrderEvidenceResponseGradeSignals {
            key,
            points,
            detail,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Key {
    #[serde(rename = "packing_capture")]
    PackingCapture,
    #[serde(rename = "continuous_take")]
    ContinuousTake,
    #[serde(rename = "seal_verified")]
    SealVerified,
    #[serde(rename = "serial_pre_recorded")]
    SerialPreRecorded,
    #[serde(rename = "serial_seen_on_frame")]
    SerialSeenOnFrame,
    #[serde(rename = "arrival_condition")]
    ArrivalCondition,
}

impl Default for Key {
    fn default() -> Key {
        Self::PackingCapture
    }
}

