/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCategoryResponse {
    #[serde(rename = "main")]
    pub main: Box<crate::models::GetCategoryResponseMain>,
    #[serde(rename = "sub")]
    pub sub: serde_json::Value,
}

impl GetCategoryResponse {
    pub fn new(main: crate::models::GetCategoryResponseMain, sub: serde_json::Value) -> GetCategoryResponse {
        GetCategoryResponse {
            main: Box::new(main),
            sub,
        }
    }
}


