/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCbxSubjectWalletResponse {
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "chain")]
    pub chain: String,
    #[serde(rename = "verifiedAt", skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<String>,
}

impl GetCbxSubjectWalletResponse {
    pub fn new(wallet_id: String, address: String, chain: String) -> GetCbxSubjectWalletResponse {
        GetCbxSubjectWalletResponse {
            wallet_id,
            address,
            chain,
            verified_at: None,
        }
    }
}


