/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetAnalyticDashboardResponseSellThrough : The context the bare rate can't carry. `tooYoungToJudge` is the  important one: a cohort measured the day its window closed has had no  time to sell, and a low number there means \"wait\", not \"bad buys\" — a  seller acting on it would stop sourcing for no reason.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticDashboardResponseSellThrough {
    #[serde(rename = "rate", skip_serializing_if = "Option::is_none")]
    pub rate: Option<f32>,
    #[serde(rename = "cohortSize")]
    pub cohort_size: f32,
    #[serde(rename = "cohortSold")]
    pub cohort_sold: f32,
    #[serde(rename = "maturityDays")]
    pub maturity_days: f32,
    #[serde(rename = "tooYoungToJudge")]
    pub too_young_to_judge: bool,
}

impl GetAnalyticDashboardResponseSellThrough {
    /// The context the bare rate can't carry. `tooYoungToJudge` is the  important one: a cohort measured the day its window closed has had no  time to sell, and a low number there means \"wait\", not \"bad buys\" — a  seller acting on it would stop sourcing for no reason.
    pub fn new(cohort_size: f32, cohort_sold: f32, maturity_days: f32, too_young_to_judge: bool) -> GetAnalyticDashboardResponseSellThrough {
        GetAnalyticDashboardResponseSellThrough {
            rate: None,
            cohort_size,
            cohort_sold,
            maturity_days,
            too_young_to_judge,
        }
    }
}


