/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCatalogLookupResponse {
    #[serde(rename = "identifier")]
    pub identifier: Box<crate::models::GetCatalogLookupResponseIdentifier>,
    #[serde(rename = "offers")]
    pub offers: Vec<crate::models::GetCatalogLookupResponseOffers>,
}

impl GetCatalogLookupResponse {
    pub fn new(identifier: crate::models::GetCatalogLookupResponseIdentifier, offers: Vec<crate::models::GetCatalogLookupResponseOffers>) -> GetCatalogLookupResponse {
        GetCatalogLookupResponse {
            identifier: Box::new(identifier),
            offers,
        }
    }
}


