/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetListingResponse {
    #[serde(rename = "platformListings")]
    pub platform_listings: Vec<crate::models::GetListingResponsePlatformListings>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "sku", skip_serializing_if = "Option::is_none")]
    pub sku: Option<String>,
    #[serde(rename = "quantity")]
    pub quantity: f32,
    #[serde(rename = "quantityAvailable")]
    pub quantity_available: f32,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    #[serde(rename = "material", skip_serializing_if = "Option::is_none")]
    pub material: Option<String>,
    #[serde(rename = "style", skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    #[serde(rename = "itemType", skip_serializing_if = "Option::is_none")]
    pub item_type: Option<String>,
    #[serde(rename = "sizeSystem", skip_serializing_if = "Option::is_none")]
    pub size_system: Option<String>,
    #[serde(rename = "color")]
    pub color: Vec<String>,
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<String>>,
    #[serde(rename = "videoUrl", skip_serializing_if = "Option::is_none")]
    pub video_url: Option<String>,
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "priceFloorCents", skip_serializing_if = "Option::is_none")]
    pub price_floor_cents: Option<f32>,
    #[serde(rename = "floorIsNet")]
    pub floor_is_net: bool,
    #[serde(rename = "weightLb", skip_serializing_if = "Option::is_none")]
    pub weight_lb: Option<String>,
    #[serde(rename = "weightOz", skip_serializing_if = "Option::is_none")]
    pub weight_oz: Option<String>,
    #[serde(rename = "dimensionLIn", skip_serializing_if = "Option::is_none")]
    pub dimension_lin: Option<String>,
    #[serde(rename = "dimensionWIn", skip_serializing_if = "Option::is_none")]
    pub dimension_win: Option<String>,
    #[serde(rename = "dimensionHIn", skip_serializing_if = "Option::is_none")]
    pub dimension_hin: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "descriptionHtml", skip_serializing_if = "Option::is_none")]
    pub description_html: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    #[serde(rename = "gradeKey", skip_serializing_if = "Option::is_none")]
    pub grade_key: Option<String>,
    #[serde(rename = "grading", skip_serializing_if = "Option::is_none")]
    pub grading: Option<Box<crate::models::ListListingsItemGrading>>,
    #[serde(rename = "publishAt", skip_serializing_if = "Option::is_none")]
    pub publish_at: Option<String>,
    #[serde(rename = "scheduledPlatforms", skip_serializing_if = "Option::is_none")]
    pub scheduled_platforms: Option<Vec<String>>,
    #[serde(rename = "parentListingId", skip_serializing_if = "Option::is_none")]
    pub parent_listing_id: Option<String>,
    #[serde(rename = "isBundle")]
    pub is_bundle: bool,
    #[serde(rename = "automationAssignedRuleIds")]
    pub automation_assigned_rule_ids: Vec<String>,
    #[serde(rename = "automationBlockedRuleIds")]
    pub automation_blocked_rule_ids: Vec<String>,
    #[serde(rename = "automationAssignedChainIds")]
    pub automation_assigned_chain_ids: Vec<String>,
    #[serde(rename = "automationBlockedChainIds")]
    pub automation_blocked_chain_ids: Vec<String>,
    #[serde(rename = "hsCode", skip_serializing_if = "Option::is_none")]
    pub hs_code: Option<String>,
    #[serde(rename = "countryOfOrigin", skip_serializing_if = "Option::is_none")]
    pub country_of_origin: Option<String>,
    #[serde(rename = "delistedAt", skip_serializing_if = "Option::is_none")]
    pub delisted_at: Option<String>,
    #[serde(rename = "soldAt", skip_serializing_if = "Option::is_none")]
    pub sold_at: Option<String>,
    #[serde(rename = "duplicateOfListingId", skip_serializing_if = "Option::is_none")]
    pub duplicate_of_listing_id: Option<String>,
    #[serde(rename = "clientDraftId", skip_serializing_if = "Option::is_none")]
    pub client_draft_id: Option<String>,
}

impl GetListingResponse {
    pub fn new(platform_listings: Vec<crate::models::GetListingResponsePlatformListings>, id: String, created_at: String, updated_at: String, user_id: String, quantity: f32, quantity_available: f32, color: Vec<String>, tags: Vec<String>, floor_is_net: bool, status: String, source: String, is_bundle: bool, automation_assigned_rule_ids: Vec<String>, automation_blocked_rule_ids: Vec<String>, automation_assigned_chain_ids: Vec<String>, automation_blocked_chain_ids: Vec<String>) -> GetListingResponse {
        GetListingResponse {
            platform_listings,
            id,
            brand: None,
            name: None,
            created_at,
            updated_at,
            user_id,
            sku: None,
            quantity,
            quantity_available,
            condition: None,
            size: None,
            material: None,
            style: None,
            pattern: None,
            department: None,
            gender: None,
            item_type: None,
            size_system: None,
            color,
            images: None,
            video_url: None,
            tags,
            price_floor_cents: None,
            floor_is_net,
            weight_lb: None,
            weight_oz: None,
            dimension_lin: None,
            dimension_win: None,
            dimension_hin: None,
            status,
            source,
            description: None,
            title: None,
            description_html: None,
            price: None,
            grade_key: None,
            grading: None,
            publish_at: None,
            scheduled_platforms: None,
            parent_listing_id: None,
            is_bundle,
            automation_assigned_rule_ids,
            automation_blocked_rule_ids,
            automation_assigned_chain_ids,
            automation_blocked_chain_ids,
            hs_code: None,
            country_of_origin: None,
            delisted_at: None,
            sold_at: None,
            duplicate_of_listing_id: None,
            client_draft_id: None,
        }
    }
}


