/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetConnectionHealthResponseLiveness {
    /// The clean \"the browser pushed cookies\" signal.
    #[serde(rename = "lastBrowserPushAt", skip_serializing_if = "Option::is_none")]
    pub last_browser_push_at: Option<String>,
    #[serde(rename = "lastBrowserPushAgo")]
    pub last_browser_push_ago: String,
    /// Also stamped by the executor on any successful server-side call, so it is NOT evidence the extension is alive. Exposed for debugging only.
    #[serde(rename = "lastSyncedAt", skip_serializing_if = "Option::is_none")]
    pub last_synced_at: Option<String>,
    /// Last server-exec attempt, success or fail.
    #[serde(rename = "lastUsedAt", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<String>,
    #[serde(rename = "lastUsedAgo")]
    pub last_used_ago: String,
    #[serde(rename = "authFailureStreak")]
    pub auth_failure_streak: f32,
}

impl GetConnectionHealthResponseLiveness {
    pub fn new(last_browser_push_ago: String, last_used_ago: String, auth_failure_streak: f32) -> GetConnectionHealthResponseLiveness {
        GetConnectionHealthResponseLiveness {
            last_browser_push_at: None,
            last_browser_push_ago,
            last_synced_at: None,
            last_used_at: None,
            last_used_ago,
            auth_failure_streak,
        }
    }
}


