/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOrderEvidenceResponse {
    #[serde(rename = "grade")]
    pub grade: Box<crate::models::GetOrderEvidenceResponseGrade>,
    #[serde(rename = "captures")]
    pub captures: Vec<crate::models::GetOrderEvidenceResponseCaptures>,
    #[serde(rename = "seal")]
    pub seal: Box<crate::models::GetOrderEvidenceResponseSeal>,
    #[serde(rename = "arrival")]
    pub arrival: Box<crate::models::GetOrderEvidenceResponseArrival>,
    #[serde(rename = "units")]
    pub units: Vec<crate::models::GetOrderEvidenceResponseUnits>,
}

impl GetOrderEvidenceResponse {
    pub fn new(grade: crate::models::GetOrderEvidenceResponseGrade, captures: Vec<crate::models::GetOrderEvidenceResponseCaptures>, seal: crate::models::GetOrderEvidenceResponseSeal, arrival: crate::models::GetOrderEvidenceResponseArrival, units: Vec<crate::models::GetOrderEvidenceResponseUnits>) -> GetOrderEvidenceResponse {
        GetOrderEvidenceResponse {
            grade: Box::new(grade),
            captures,
            seal: Box::new(seal),
            arrival: Box::new(arrival),
            units,
        }
    }
}


