/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetSpatialPublicResponseStats : Only the count. `capitalCents` is the seller's spend and never leaves.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSpatialPublicResponseStats {
    #[serde(rename = "itemCount")]
    pub item_count: f32,
}

impl GetSpatialPublicResponseStats {
    /// Only the count. `capitalCents` is the seller's spend and never leaves.
    pub fn new(item_count: f32) -> GetSpatialPublicResponseStats {
        GetSpatialPublicResponseStats {
            item_count,
        }
    }
}


