/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTaxonomyRequiredFieldResponseRequiredFields {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "master")]
    pub master: bool,
    #[serde(rename = "required")]
    pub required: bool,
    #[serde(rename = "dataType")]
    pub data_type: DataType,
    #[serde(rename = "hasEnumValues")]
    pub has_enum_values: bool,
    #[serde(rename = "enumValues", skip_serializing_if = "Option::is_none")]
    pub enum_values: Option<Vec<String>>,
    #[serde(rename = "hint", skip_serializing_if = "Option::is_none")]
    pub hint: Option<String>,
}

impl GetTaxonomyRequiredFieldResponseRequiredFields {
    pub fn new(key: String, label: String, master: bool, required: bool, data_type: DataType, has_enum_values: bool) -> GetTaxonomyRequiredFieldResponseRequiredFields {
        GetTaxonomyRequiredFieldResponseRequiredFields {
            key,
            label,
            master,
            required,
            data_type,
            has_enum_values,
            enum_values: None,
            hint: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "STRING")]
    STRING,
    #[serde(rename = "NUMBER")]
    NUMBER,
    #[serde(rename = "BOOLEAN")]
    BOOLEAN,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::STRING
    }
}

