/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOfferResponseOffers {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "amountCents")]
    pub amount_cents: f32,
    /// Asking total when the offer was made — what the buyer responded to.
    #[serde(rename = "listedTotalCents", skip_serializing_if = "Option::is_none")]
    pub listed_total_cents: Option<f32>,
    #[serde(rename = "isBundle")]
    pub is_bundle: bool,
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "parentOfferId", skip_serializing_if = "Option::is_none")]
    pub parent_offer_id: Option<String>,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
    #[serde(rename = "decidedAt", skip_serializing_if = "Option::is_none")]
    pub decided_at: Option<String>,
    /// Set once an accepted offer has actually been paid for.
    #[serde(rename = "consumedAt", skip_serializing_if = "Option::is_none")]
    pub consumed_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl GetOfferResponseOffers {
    pub fn new(id: String, status: String, amount_cents: f32, is_bundle: bool, items: Vec<serde_json::Value>, expires_at: String, created_at: String) -> GetOfferResponseOffers {
        GetOfferResponseOffers {
            id,
            status,
            amount_cents,
            listed_total_cents: None,
            is_bundle,
            items,
            message: None,
            parent_offer_id: None,
            expires_at,
            decided_at: None,
            consumed_at: None,
            created_at,
        }
    }
}


