/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSpatialPublicResponseProfileContainers {
    /// Stable key. Persisted on every placement — never renamed.
    #[serde(rename = "key")]
    pub key: String,
    /// What the seller calls it. \"Page 3\", \"Case\", \"Long box\".
    #[serde(rename = "label")]
    pub label: String,
    /// Which hand-authored mesh renders this container. A small closed set — the  art budget lives here and nowhere else.
    #[serde(rename = "model")]
    pub model: String,
    /// Outer bounds, for packing containers into a room.
    #[serde(rename = "size")]
    pub size: serde_json::Value,
    #[serde(rename = "slots")]
    pub slots: serde_json::Value,
}

impl GetSpatialPublicResponseProfileContainers {
    pub fn new(key: String, label: String, model: String, size: serde_json::Value, slots: serde_json::Value) -> GetSpatialPublicResponseProfileContainers {
        GetSpatialPublicResponseProfileContainers {
            key,
            label,
            model,
            size,
            slots,
        }
    }
}


