/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetSpatialPublicResponseProfileItemSize : Fallback physical size of one item. Used when the catalog does not publish  real dimensions for this product. See the module docblock: where the  catalog knows, the catalog wins.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSpatialPublicResponseProfileItemSize {
    #[serde(rename = "x")]
    pub x: f32,
    #[serde(rename = "y")]
    pub y: f32,
    #[serde(rename = "z")]
    pub z: f32,
}

impl GetSpatialPublicResponseProfileItemSize {
    /// Fallback physical size of one item. Used when the catalog does not publish  real dimensions for this product. See the module docblock: where the  catalog knows, the catalog wins.
    pub fn new(x: f32, y: f32, z: f32) -> GetSpatialPublicResponseProfileItemSize {
        GetSpatialPublicResponseProfileItemSize {
            x,
            y,
            z,
        }
    }
}


