/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPlatformLimitResponse {
    #[serde(rename = "ebay", skip_serializing_if = "Option::is_none")]
    pub ebay: Option<Box<crate::models::GetPlatformLimitResponseEbay>>,
    #[serde(rename = "etsy", skip_serializing_if = "Option::is_none")]
    pub etsy: Option<Box<crate::models::GetPlatformLimitResponseEtsy>>,
}

impl GetPlatformLimitResponse {
    pub fn new() -> GetPlatformLimitResponse {
        GetPlatformLimitResponse {
            ebay: None,
            etsy: None,
        }
    }
}


