/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticTimeseryResponse {
    #[serde(rename = "days")]
    pub days: f32,
    #[serde(rename = "series")]
    pub series: Vec<crate::models::GetAnalyticTimeseryResponseSeries>,
}

impl GetAnalyticTimeseryResponse {
    pub fn new(days: f32, series: Vec<crate::models::GetAnalyticTimeseryResponseSeries>) -> GetAnalyticTimeseryResponse {
        GetAnalyticTimeseryResponse {
            days,
            series,
        }
    }
}


