/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAnalyticBookkeepingResponseMonthlyPl {
    #[serde(rename = "month")]
    pub month: f32,
    #[serde(rename = "revenue")]
    pub revenue: f32,
    #[serde(rename = "cogs")]
    pub cogs: f32,
    #[serde(rename = "platformFees")]
    pub platform_fees: f32,
    #[serde(rename = "shippingCosts")]
    pub shipping_costs: f32,
    #[serde(rename = "netProfit")]
    pub net_profit: f32,
}

impl GetAnalyticBookkeepingResponseMonthlyPl {
    pub fn new(month: f32, revenue: f32, cogs: f32, platform_fees: f32, shipping_costs: f32, net_profit: f32) -> GetAnalyticBookkeepingResponseMonthlyPl {
        GetAnalyticBookkeepingResponseMonthlyPl {
            month,
            revenue,
            cogs,
            platform_fees,
            shipping_costs,
            net_profit,
        }
    }
}


