/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTaxScheduleCResponseExpenses {
    #[serde(rename = "platformFees")]
    pub platform_fees: f32,
    #[serde(rename = "shippingExpenses")]
    pub shipping_expenses: f32,
    #[serde(rename = "costOfGoodsSold")]
    pub cost_of_goods_sold: f32,
    #[serde(rename = "carAndTruckMileage")]
    pub car_and_truck_mileage: f32,
    #[serde(rename = "carAndTruckMiles")]
    pub car_and_truck_miles: f32,
}

impl GetTaxScheduleCResponseExpenses {
    pub fn new(platform_fees: f32, shipping_expenses: f32, cost_of_goods_sold: f32, car_and_truck_mileage: f32, car_and_truck_miles: f32) -> GetTaxScheduleCResponseExpenses {
        GetTaxScheduleCResponseExpenses {
            platform_fees,
            shipping_expenses,
            cost_of_goods_sold,
            car_and_truck_mileage,
            car_and_truck_miles,
        }
    }
}


