/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetAutomationRuleExportResponseMetadata : Community-library metadata. Server ignores; UI may render.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAutomationRuleExportResponseMetadata {
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "sourceUrl", skip_serializing_if = "Option::is_none")]
    pub source_url: Option<String>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
}

impl GetAutomationRuleExportResponseMetadata {
    /// Community-library metadata. Server ignores; UI may render.
    pub fn new() -> GetAutomationRuleExportResponseMetadata {
        GetAutomationRuleExportResponseMetadata {
            tags: None,
            source_url: None,
            author: None,
        }
    }
}


