/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAiStatusResponseCustomConfig {
    #[serde(rename = "baseUrl")]
    pub base_url: String,
    #[serde(rename = "textModel")]
    pub text_model: String,
    #[serde(rename = "visionModel", skip_serializing_if = "Option::is_none")]
    pub vision_model: Option<String>,
    #[serde(rename = "supportsVision")]
    pub supports_vision: bool,
    #[serde(rename = "supportsJsonMode")]
    pub supports_json_mode: bool,
}

impl GetAiStatusResponseCustomConfig {
    pub fn new(base_url: String, text_model: String, supports_vision: bool, supports_json_mode: bool) -> GetAiStatusResponseCustomConfig {
        GetAiStatusResponseCustomConfig {
            base_url,
            text_model,
            vision_model: None,
            supports_vision,
            supports_json_mode,
        }
    }
}


