/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListCbxCampaignPayoutsItem {
    #[serde(rename = "subjectId")]
    pub subject_id: String,
    #[serde(rename = "weight")]
    pub weight: String,
    #[serde(rename = "baseUnits")]
    pub base_units: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl ListCbxCampaignPayoutsItem {
    pub fn new(subject_id: String, weight: String, base_units: String, created_at: String) -> ListCbxCampaignPayoutsItem {
        ListCbxCampaignPayoutsItem {
            subject_id,
            weight,
            base_units,
            created_at,
        }
    }
}


