/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListInventoryUnitsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    #[serde(rename = "soldAt", skip_serializing_if = "Option::is_none")]
    pub sold_at: Option<String>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "identifiers")]
    pub identifiers: Vec<crate::models::ListInventoryUnitsItemIdentifiers>,
}

impl ListInventoryUnitsItem {
    pub fn new(id: String, status: String, created_at: String, identifiers: Vec<crate::models::ListInventoryUnitsItemIdentifiers>) -> ListInventoryUnitsItem {
        ListInventoryUnitsItem {
            id,
            status,
            order_id: None,
            sold_at: None,
            notes: None,
            created_at,
            identifiers,
        }
    }
}


