/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListSpatialPublicItem {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "publicSlug")]
    pub public_slug: String,
    #[serde(rename = "categorySlug")]
    pub category_slug: String,
    /// Unsold stock that lands in this room. The same predicate the room uses.
    #[serde(rename = "itemCount")]
    pub item_count: f32,
    /// How many of those a visitor could buy right now.
    #[serde(rename = "forSaleCount")]
    pub for_sale_count: f32,
    /// The cheapest and dearest thing for sale, in cents.  A BAND, deliberately, and never a quote: `listPublicSceneOffers` is the only authority on what a given object costs. Null when nothing is for sale — zero would read as free.
    #[serde(rename = "priceFromCents", skip_serializing_if = "Option::is_none")]
    pub price_from_cents: Option<f32>,
    #[serde(rename = "priceToCents", skip_serializing_if = "Option::is_none")]
    pub price_to_cents: Option<f32>,
    /// Up to PREVIEW_IMAGES item images. Catalog art first, seller photo else.
    #[serde(rename = "previewImages")]
    pub preview_images: Vec<String>,
    /// Last time the room itself changed. ISO, or null if the row has no date.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ListSpatialPublicItem {
    pub fn new(name: String, public_slug: String, category_slug: String, item_count: f32, for_sale_count: f32, preview_images: Vec<String>) -> ListSpatialPublicItem {
        ListSpatialPublicItem {
            name,
            public_slug,
            category_slug,
            item_count,
            for_sale_count,
            price_from_cents: None,
            price_to_cents: None,
            preview_images,
            updated_at: None,
        }
    }
}


