/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListInsightByPlatformItem {
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "sales")]
    pub sales: String,
    #[serde(rename = "gross_cents")]
    pub gross_cents: String,
    #[serde(rename = "avg_days_to_sale")]
    pub avg_days_to_sale: f32,
    #[serde(rename = "avg_sale_cents")]
    pub avg_sale_cents: f32,
    #[serde(rename = "net_cents")]
    pub net_cents: String,
}

impl ListInsightByPlatformItem {
    pub fn new(platform: String, sales: String, gross_cents: String, avg_days_to_sale: f32, avg_sale_cents: f32, net_cents: String) -> ListInsightByPlatformItem {
        ListInsightByPlatformItem {
            platform,
            sales,
            gross_cents,
            avg_days_to_sale,
            avg_sale_cents,
            net_cents,
        }
    }
}


