/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListCbxRedemptionServicesItem {
    #[serde(rename = "serviceKind")]
    pub service_kind: String,
    #[serde(rename = "label")]
    pub label: Label,
}

impl ListCbxRedemptionServicesItem {
    pub fn new(service_kind: String, label: Label) -> ListCbxRedemptionServicesItem {
        ListCbxRedemptionServicesItem {
            service_kind,
            label,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Label {
    #[serde(rename = "Card / comic grading submission")]
    CardComicGradingSubmission,
    #[serde(rename = "Item authentication")]
    ItemAuthentication,
    #[serde(rename = "Evidence seal (condition proof)")]
    EvidenceSealConditionProof,
    #[serde(rename = "Crossly subscription")]
    CrosslySubscription,
}

impl Default for Label {
    fn default() -> Label {
        Self::CardComicGradingSubmission
    }
}

