/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListCbxDisbursementRulesItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "thresholdBaseUnits")]
    pub threshold_base_units: String,
    #[serde(rename = "distributeBps")]
    pub distribute_bps: f32,
    #[serde(rename = "checkCadenceHours")]
    pub check_cadence_hours: f32,
    #[serde(rename = "requireCoverageBps")]
    pub require_coverage_bps: f32,
    #[serde(rename = "metric")]
    pub metric: String,
    #[serde(rename = "lookbackDays")]
    pub lookback_days: f32,
    #[serde(rename = "maxRecipients")]
    pub max_recipients: f32,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "lastFiredAt", skip_serializing_if = "Option::is_none")]
    pub last_fired_at: Option<String>,
}

impl ListCbxDisbursementRulesItem {
    pub fn new(id: String, name: String, threshold_base_units: String, distribute_bps: f32, check_cadence_hours: f32, require_coverage_bps: f32, metric: String, lookback_days: f32, max_recipients: f32, is_active: bool) -> ListCbxDisbursementRulesItem {
        ListCbxDisbursementRulesItem {
            id,
            name,
            threshold_base_units,
            distribute_bps,
            check_cadence_hours,
            require_coverage_bps,
            metric,
            lookback_days,
            max_recipients,
            is_active,
            last_fired_at: None,
        }
    }
}


