/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListListingDiscrepanciesItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "listingId")]
    pub listing_id: String,
    #[serde(rename = "accountSlot")]
    pub account_slot: f32,
    #[serde(rename = "lastError", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "ourValue", skip_serializing_if = "Option::is_none")]
    pub our_value: Option<String>,
    #[serde(rename = "remoteValue", skip_serializing_if = "Option::is_none")]
    pub remote_value: Option<String>,
    #[serde(rename = "firstDetectedAt")]
    pub first_detected_at: String,
    #[serde(rename = "lastDetectedAt")]
    pub last_detected_at: String,
    #[serde(rename = "dismissedAt", skip_serializing_if = "Option::is_none")]
    pub dismissed_at: Option<String>,
    #[serde(rename = "dismissedRemoteValue", skip_serializing_if = "Option::is_none")]
    pub dismissed_remote_value: Option<String>,
}

impl ListListingDiscrepanciesItem {
    pub fn new(id: String, created_at: String, updated_at: String, user_id: String, source: String, platform: String, listing_id: String, account_slot: f32, field: String, first_detected_at: String, last_detected_at: String) -> ListListingDiscrepanciesItem {
        ListListingDiscrepanciesItem {
            id,
            created_at,
            updated_at,
            user_id,
            source,
            platform,
            listing_id,
            account_slot,
            last_error: None,
            field,
            our_value: None,
            remote_value: None,
            first_detected_at,
            last_detected_at,
            dismissed_at: None,
            dismissed_remote_value: None,
        }
    }
}


