/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAutomationRunsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "durationMs", skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<f32>,
    #[serde(rename = "actionType")]
    pub action_type: String,
    #[serde(rename = "ruleId", skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<String>,
    #[serde(rename = "chainId", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<String>,
}

impl ListAutomationRunsItem {
    pub fn new(id: String, created_at: String, user_id: String, status: String, action_type: String) -> ListAutomationRunsItem {
        ListAutomationRunsItem {
            id,
            created_at,
            user_id,
            status,
            error_message: None,
            duration_ms: None,
            action_type,
            rule_id: None,
            chain_id: None,
        }
    }
}


