/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListCompWatchlistRecentItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(rename = "sold_price")]
    pub sold_price: String,
    #[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[serde(rename = "listing_url", skip_serializing_if = "Option::is_none")]
    pub listing_url: Option<String>,
    #[serde(rename = "scraped_at")]
    pub scraped_at: String,
    #[serde(rename = "sold_at_approx", skip_serializing_if = "Option::is_none")]
    pub sold_at_approx: Option<String>,
}

impl ListCompWatchlistRecentItem {
    pub fn new(id: String, platform: String, title: String, sold_price: String, scraped_at: String) -> ListCompWatchlistRecentItem {
        ListCompWatchlistRecentItem {
            id,
            platform,
            title,
            brand: None,
            sold_price,
            image_url: None,
            listing_url: None,
            scraped_at,
            sold_at_approx: None,
        }
    }
}


