/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListMarketGradersItem {
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "categorySlugs")]
    pub category_slugs: Vec<String>,
    #[serde(rename = "scale")]
    pub scale: Scale,
    #[serde(rename = "grades")]
    pub grades: Vec<String>,
    #[serde(rename = "qualifiers")]
    pub qualifiers: Vec<String>,
    #[serde(rename = "sealGrades")]
    pub seal_grades: Vec<String>,
}

impl ListMarketGradersItem {
    pub fn new(slug: String, name: String, category_slugs: Vec<String>, scale: Scale, grades: Vec<String>, qualifiers: Vec<String>, seal_grades: Vec<String>) -> ListMarketGradersItem {
        ListMarketGradersItem {
            slug,
            name,
            category_slugs,
            scale,
            grades,
            qualifiers,
            seal_grades,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scale {
    #[serde(rename = "numeric")]
    Numeric,
    #[serde(rename = "sheldon")]
    Sheldon,
    #[serde(rename = "dual")]
    Dual,
    #[serde(rename = "hundred")]
    Hundred,
}

impl Default for Scale {
    fn default() -> Scale {
        Self::Numeric
    }
}

