/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListWorkflowChainsItem {
    #[serde(rename = "steps")]
    pub steps: Vec<crate::models::ListWorkflowChainsItemSteps>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "triggerId")]
    pub trigger_id: String,
}

impl ListWorkflowChainsItem {
    pub fn new(steps: Vec<crate::models::ListWorkflowChainsItemSteps>, id: String, name: String, created_at: String, user_id: String, is_active: bool, trigger_id: String) -> ListWorkflowChainsItem {
        ListWorkflowChainsItem {
            steps,
            id,
            name,
            created_at,
            user_id,
            is_active,
            trigger_id,
        }
    }
}


