/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListCbxStakeTiersItem {
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "minBaseUnits")]
    pub min_base_units: String,
    #[serde(rename = "feeDiscountBps")]
    pub fee_discount_bps: f32,
    #[serde(rename = "earnBoostBps")]
    pub earn_boost_bps: f32,
    #[serde(rename = "cooldownDays")]
    pub cooldown_days: f32,
}

impl ListCbxStakeTiersItem {
    pub fn new(slug: String, label: String, min_base_units: String, fee_discount_bps: f32, earn_boost_bps: f32, cooldown_days: f32) -> ListCbxStakeTiersItem {
        ListCbxStakeTiersItem {
            slug,
            label,
            min_base_units,
            fee_discount_bps,
            earn_boost_bps,
            cooldown_days,
        }
    }
}


