/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListMeTemplatesItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    #[serde(rename = "material", skip_serializing_if = "Option::is_none")]
    pub material: Option<String>,
    #[serde(rename = "style", skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    #[serde(rename = "itemType", skip_serializing_if = "Option::is_none")]
    pub item_type: Option<String>,
    #[serde(rename = "sizeSystem", skip_serializing_if = "Option::is_none")]
    pub size_system: Option<String>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "weightOz", skip_serializing_if = "Option::is_none")]
    pub weight_oz: Option<f32>,
    #[serde(rename = "isDefault")]
    pub is_default: bool,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "scope")]
    pub scope: String,
    #[serde(rename = "shareToken", skip_serializing_if = "Option::is_none")]
    pub share_token: Option<String>,
    #[serde(rename = "descriptionVariants", skip_serializing_if = "Option::is_none")]
    pub description_variants: Option<Vec<String>>,
    #[serde(rename = "titleVariants", skip_serializing_if = "Option::is_none")]
    pub title_variants: Option<Vec<String>>,
    #[serde(rename = "defaultForCategory", skip_serializing_if = "Option::is_none")]
    pub default_for_category: Option<String>,
    #[serde(rename = "sortOrder")]
    pub sort_order: f32,
}

impl ListMeTemplatesItem {
    pub fn new(id: String, name: String, created_at: String, updated_at: String, user_id: String, is_default: bool, scope: String, sort_order: f32) -> ListMeTemplatesItem {
        ListMeTemplatesItem {
            id,
            brand: None,
            name,
            created_at,
            updated_at,
            user_id,
            condition: None,
            size: None,
            material: None,
            style: None,
            pattern: None,
            department: None,
            gender: None,
            item_type: None,
            size_system: None,
            color: None,
            tags: None,
            notes: None,
            weight_oz: None,
            is_default,
            description: None,
            title: None,
            scope,
            share_token: None,
            description_variants: None,
            title_variants: None,
            default_for_category: None,
            sort_order,
        }
    }
}


