/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListConnectedAppsItem {
    #[serde(rename = "grantId")]
    pub grant_id: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "connectedAt")]
    pub connected_at: String,
    #[serde(rename = "lastUsedAt", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<String>,
    #[serde(rename = "appId")]
    pub app_id: String,
    #[serde(rename = "appName")]
    pub app_name: String,
    #[serde(rename = "appDescription", skip_serializing_if = "Option::is_none")]
    pub app_description: Option<String>,
    #[serde(rename = "homepageUrl", skip_serializing_if = "Option::is_none")]
    pub homepage_url: Option<String>,
    #[serde(rename = "developerName", skip_serializing_if = "Option::is_none")]
    pub developer_name: Option<String>,
    #[serde(rename = "developerEmail")]
    pub developer_email: String,
}

impl ListConnectedAppsItem {
    pub fn new(grant_id: String, scopes: Vec<String>, connected_at: String, app_id: String, app_name: String, developer_email: String) -> ListConnectedAppsItem {
        ListConnectedAppsItem {
            grant_id,
            scopes,
            connected_at,
            last_used_at: None,
            app_id,
            app_name,
            app_description: None,
            homepage_url: None,
            developer_name: None,
            developer_email,
        }
    }
}


