/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListInventoryUnitsItemIdentifiers {
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "recordedAt")]
    pub recorded_at: String,
    #[serde(rename = "strength")]
    pub strength: Strength,
}

impl ListInventoryUnitsItemIdentifiers {
    pub fn new(namespace: String, value: String, source: String, recorded_at: String, strength: Strength) -> ListInventoryUnitsItemIdentifiers {
        ListInventoryUnitsItemIdentifiers {
            namespace,
            value,
            source,
            recorded_at,
            strength,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Strength {
    #[serde(rename = "strong")]
    Strong,
    #[serde(rename = "good")]
    Good,
    #[serde(rename = "weak")]
    Weak,
}

impl Default for Strength {
    fn default() -> Strength {
        Self::Strong
    }
}

