/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAuthSessionsItem {
    #[serde(rename = "isCurrent")]
    pub is_current: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "userAgent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[serde(rename = "ipAddress", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(rename = "ipCountry", skip_serializing_if = "Option::is_none")]
    pub ip_country: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "lastUsedAt")]
    pub last_used_at: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
}

impl ListAuthSessionsItem {
    pub fn new(is_current: bool, id: String, created_at: String, last_used_at: String, expires_at: String) -> ListAuthSessionsItem {
        ListAuthSessionsItem {
            is_current,
            id,
            user_agent: None,
            ip_address: None,
            ip_country: None,
            created_at,
            last_used_at,
            expires_at,
        }
    }
}


