/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdatePolicyPresetResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    /// 'return' | 'shipping' | 'payment' — validated at the route layer.
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name")]
    pub name: String,
    /// Auto-selected on new listings. At most one true per (user, kind).
    #[serde(rename = "isDefault")]
    pub is_default: bool,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl UpdatePolicyPresetResponse {
    pub fn new(id: String, user_id: String, kind: String, name: String, is_default: bool, created_at: String, updated_at: String) -> UpdatePolicyPresetResponse {
        UpdatePolicyPresetResponse {
            id,
            user_id,
            kind,
            name,
            is_default,
            created_at,
            updated_at,
        }
    }
}


