/*
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateMileageResponse {
    #[serde(rename = "miles")]
    pub miles: f32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "purpose")]
    pub purpose: String,
    #[serde(rename = "startLocation", skip_serializing_if = "Option::is_none")]
    pub start_location: Option<String>,
    #[serde(rename = "endLocation", skip_serializing_if = "Option::is_none")]
    pub end_location: Option<String>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl UpdateMileageResponse {
    pub fn new(miles: f32, id: String, user_id: String, date: String, purpose: String, created_at: String) -> UpdateMileageResponse {
        UpdateMileageResponse {
            miles,
            id,
            user_id,
            date,
            purpose,
            start_location: None,
            end_location: None,
            notes: None,
            created_at,
        }
    }
}


